amelioro/ameliorate

.github/workflows/ci.yml
web/package.json

ci: add lint action

---

web/public/examples/abortion.json
web/public/examples/world_hunger.json
web/src/modules/topic/components/ScoreEdge/ScoreEdge.tsx
web/src/modules/topic/utils/diagram.ts

Closes #20 
- markerStart wasn't being passed to the custom edge, so needed to add that
- change to edge state requires updating the example json's
-

20 give edges a direction

---

web/public/examples/abortion.json
web/public/examples/world_hunger.json
web/src/modules/topic/components/AddNodeButton/AddNodeButton.tsx
web/src/modules/topic/components/AddNodeButtonGroup/AddNodeButtonGroup.stories.tsx
web/src/modules/topic/components/AddNodeButtonGroup/AddNodeButtonGroup.tsx
web/src/modules/topic/components/EditableNode/EditableNode.styles.tsx
web/src/modules/topic/components/EditableNode/EditableNode.tsx
web/src/modules/topic/components/ScoreDial/ScoreDial.tsx
web/src/modules/topic/components/ScoreEdge/ScoreEdge.tsx
web/src/modules/topic/store/actions.ts
web/src/modules/topic/store/migrate.ts
web/src/modules/topic/store/store.ts
web/src/modules/topic/utils/diagram.ts
web/src/modules/topic/utils/layout.ts
web/src/modules/topic/utils/nodes.ts

Closes #21
- some renaming to address naming collisions
- specify diagram type (because future things will probably be inferred by this and direction already can be inferred from it)
- adjust a few sizes to accommodate edge label
- model relations in order to accommodate edge label
- add edge label
- any store changes need to be migrated to maintain browser localstorage, figured that out
-

21 add labels to edges

---

web/src/modules/topic/components/ScoreDial/ScoreDial.tsx
web/src/modules/topic/store/actions.ts
web/src/modules/topic/store/store.ts
web/src/modules/topic/utils/claim.ts
web/src/modules/topic/utils/diagram.ts
web/src/modules/topic/utils/nodes.ts

22 default text for implicit claim nodes

---

web/src/modules/topic/components/EditableNode/EditableNode.tsx
web/src/modules/topic/components/ScoreDial/ScoreDial.stories.tsx
web/src/modules/topic/components/ScoreDial/ScoreDial.tsx
web/src/modules/topic/components/ScoreEdge/ScoreEdge.tsx
web/src/modules/topic/store/actions.ts
web/src/modules/topic/utils/claim.ts
web/src/modules/topic/utils/diagram.ts

2 root claim score should match parent score

---

web/src/modules/topic/components/AddNodeButton/AddNodeButton.tsx
web/src/modules/topic/components/AddNodeButtonGroup/AddNodeButtonGroup.tsx
web/src/modules/topic/components/Diagram/Diagram.tsx
web/src/modules/topic/store/actions.ts
web/src/modules/topic/utils/diagram.ts
web/src/modules/topic/utils/edge.ts
web/src/modules/topic/utils/layout.ts
web/src/modules/topic/utils/nodes.ts

17 connect existing nodes

---

README.md
web/src/common/theme.ts
web/src/modules/topic/components/AddNodeButton/AddNodeButton.tsx
web/src/modules/topic/components/AddNodeButtonGroup/AddNodeButtonGroup.stories.tsx
web/src/modules/topic/components/AddNodeButtonGroup/AddNodeButtonGroup.tsx
web/src/modules/topic/components/Diagram/Diagram.tsx
web/src/modules/topic/components/EditableNode/EditableNode.tsx
web/src/modules/topic/store/actions.ts
web/src/modules/topic/utils/edge.ts
web/src/modules/topic/utils/nodes.ts

24 add solution criteria

---

web/src/common/components/Menu/Menu.tsx
web/src/common/hooks.ts
web/src/common/store/contextMenuActions.ts
web/src/common/store/contextMenuStore.ts
web/src/modules/topic/components/CriteriaIndicator/CriteriaIndicator.tsx
web/src/modules/topic/components/Diagram/Diagram.tsx
web/src/modules/topic/components/EditableNode/EditableNode.tsx
web/src/modules/topic/components/TopicToolbar/TopicToolbar.tsx
web/src/modules/topic/store/actions.ts
web/src/modules/topic/store/nodeHooks.ts
web/src/modules/topic/store/store.ts
web/src/modules/topic/utils/diagram.ts
web/src/modules/topic/utils/nodes.ts

3 delete node

---

web/src/modules/topic/components/TopicToolbar/TopicToolbar.tsx
web/src/modules/topic/store/actions.ts
web/src/modules/topic/store/store.ts

feat: reset topic

---

web/package-lock.json
web/package.json
web/src/common/store/contextMenuStore.ts
web/src/modules/topic/components/TopicToolbar/TopicToolbar.tsx
web/src/modules/topic/store/actions.ts
web/src/modules/topic/store/store.ts

Closes #1 
- grouping undo/redo actions that take place within 1 second of each other. mainly for the sake of grouping label changes from separate letter diffs into bigger diffs

1 topic undoredo

---

web/package-lock.json
web/package.json
web/src/pages/_app.tsx

chore: add google analytics

---

web/src/common/store/contextMenuStore.ts
web/src/modules/topic/components/Diagram/Diagram.tsx
web/src/modules/topic/components/EditableNode/EditableNode.tsx
web/src/pages/index.tsx

refactor: node own context click instead of flow

---

web/src/modules/topic/components/Diagram/Diagram.styles.tsx
web/src/modules/topic/components/Diagram/Diagram.tsx
web/src/modules/topic/components/TopicPane/TopicPane.styles.tsx
web/src/modules/topic/components/TopicPane/TopicPane.tsx
web/src/pages/index.tsx

Overlay claim diagram

---

web/public/examples/ameliorate.json
web/public/examples/living_location.json
web/public/examples/unwanted_pregnancy.json
web/public/examples/world_hunger.json
web/src/modules/topic/store/migrate.ts
web/src/modules/topic/utils/diagram.ts

examples were not able to have new nodes added because they were not migrated correctly when id was added to Diagram
- 
-

fix: examples can have new nodes added

---

web/src/modules/topic/components/TopicToolbar/TopicToolbar.tsx

- For the following Menu buttons: [undo, redo, download, upload, reset]. Added text descriptions when hovered  and audio readout.
-  Gives additional context to button actions for hearing impaired & user hover actions.

Added titles and aria-labels to menu icons without text

---

web/src/modules/topic/components/CriteriaTable/CriteriaTable.tsx
web/src/modules/topic/components/Diagram/Diagram.tsx

- forgot to limit viewport updating to the diagram that's having a node added to it
-

Only update relevant diagram's viewport on node add

---

web/src/modules/topic/components/Diagram/Diagram.styles.tsx
web/src/modules/topic/components/EditableNode/EditableNode.styles.tsx
web/src/modules/topic/components/TopicPane/TopicPane.tsx
web/src/modules/topic/store/store.ts

- 
- some easy QoL discovered while making an example topic

Qol improvements

---

web/package-lock.json
web/package.json
web/src/modules/topic/components/CriteriaTable/CriteriaTable.tsx
web/src/modules/topic/components/Indicator/EdgeIndicatorGroup.tsx
web/src/modules/topic/components/ScoreDial/ScoreDial.styles.tsx
web/src/modules/topic/components/ScoreDial/ScoreDial.tsx
web/src/modules/topic/components/ScorePie/ScorePie.tsx

Partially addresses #19 
- select score via pie
- react-minimal-pie-chart is a small library with seemingly enough to do what we need. more popular and easier customization than react-pie-menu

Score pie menu

---

CONTRIBUTING.md

- Add command to enable commit husky hooks

docs: husky activation bash script

---

web/public/examples/economic_system.json
web/src/common/theme.ts
web/src/modules/topic/components/Diagram/Diagram.tsx
web/src/modules/topic/store/actions.ts
web/src/modules/topic/utils/diagram.ts
web/src/modules/topic/utils/edge.ts
web/src/modules/topic/utils/node.ts

Closes #67 
- add effect node type
-

feat: add effect node type

---

web/package-lock.json
web/package.json

Closes #72 
- just upgrading react-flow because that repo fixed this issue
-

72 panning sometimes suddenly stops working

---

web/src/common/components/ContextMenu/ContextMenu.tsx
web/src/common/components/ContextMenu/DeleteEdgeMenuItem.tsx
web/src/common/store/contextMenuStore.ts
web/src/modules/topic/components/ScoreEdge/ScoreEdge.tsx
web/src/modules/topic/store/actions.ts

Closes #94
- allow deleting edges
-

94 delete edges

---

web/src/modules/topic/components/CriteriaTable/CriteriaTable.styles.tsx
web/src/modules/topic/components/CriteriaTable/CriteriaTable.tsx
web/src/modules/topic/components/Node/AddNodeButton.tsx
web/src/pages/index.page.tsx
web/src/pages/index.styles.tsx

Partially addresses #74 
- Updated the Criteria Table component to have tool bar
- Fixed table workspace to take up the entire area

feat: mui table fits workspace

---

web/public/examples/ameliorate.json
web/public/examples/economic_system.json
web/public/examples/living_location.json
web/public/examples/unwanted_pregnancy.json
web/public/examples/world_hunger.json
web/src/common/components/ContextMenu/ContextMenu.tsx
web/src/common/components/ContextMenu/ShowComponentsMenuItem.tsx
web/src/common/components/ContextMenu/ShowCriteriaMenuItem.tsx
web/src/common/components/ContextMenu/ShowEffectsMenuItem.tsx
web/src/common/components/ContextMenu/ShowImpliedEdgesMenuItem.tsx
web/src/modules/topic/components/Surface/TopicToolbar.tsx
web/src/modules/topic/store/actions.ts
web/src/modules/topic/store/createDeleteActions.ts
web/src/modules/topic/store/migrate.ts
web/src/modules/topic/store/nodeHooks.ts
web/src/modules/topic/store/store.ts
web/src/modules/topic/store/viewActions.ts
web/src/modules/topic/utils/diagram.ts
web/src/modules/topic/utils/edge.ts
web/src/modules/topic/utils/node.ts

100 optionally allow hiding components effects implied edges

---

web/src/modules/topic/components/Score/Score.styles.tsx
web/src/pages/index.page.tsx
web/src/pages/index.styles.tsx

- added "buffer" circle behind score pie; catches segment rendering edge cases
- added conditional overflow hidden on body when workspace is rendered.

Improve score pie uiux

---

web/src/modules/topic/components/Diagram/Diagram.styles.tsx
web/src/modules/topic/components/Diagram/Diagram.tsx
web/src/modules/topic/components/Node/EditableNode.tsx
web/src/modules/topic/components/Node/FlowNode.styles.tsx
web/src/modules/topic/components/Node/FlowNode.tsx
web/src/modules/topic/components/ScoreEdge/ScoreEdge.styles.tsx
web/src/modules/topic/components/ScoreEdge/ScoreEdge.tsx
web/src/modules/topic/store/actions.ts
web/src/modules/topic/store/arguableHooks.ts
web/src/modules/topic/store/edgeHooks.ts
web/src/modules/topic/store/nodeHooks.ts
web/src/modules/topic/utils/diagram.ts
web/src/modules/topic/utils/edge.ts
web/src/modules/topic/utils/node.ts

32 highlight elevate connected edges on node select hover

---

CONTRIBUTING.md
web/docs/uxui-guidelines.md
web/src/modules/topic/components/CriteriaTable/CriteriaTable.styles.tsx
web/src/modules/topic/components/CriteriaTable/CriteriaTable.tsx
web/src/modules/topic/components/CriteriaTable/NodeCell.styles.tsx
web/src/modules/topic/components/Indicator/Indicator.styles.tsx
web/src/modules/topic/components/Node/EditableNode.styles.tsx
web/src/modules/topic/components/Node/EditableNode.tsx
web/src/modules/topic/components/Score/Score.styles.tsx
web/src/modules/topic/components/Score/Score.tsx
web/src/modules/topic/components/Surface/TopicPane.styles.tsx
web/src/modules/topic/hooks/flowHooks.ts
web/src/modules/topic/utils/layout.ts
web/src/modules/topic/utils/node.ts
web/src/pages/_document.page.tsx

- Changed various components to scale with rem units: Topic Drawer, Criteria Table, Editable Node, Score Button
- Added documentation on sizing fonts and components

Convert to rem units

---

CONTRIBUTING.md

docs(contributing): mention all-contributors

---

web/public/examples/economic_system.json
web/public/examples/living_location.json
web/public/examples/unwanted_pregnancy.json
web/public/examples/world_hunger.json
web/src/modules/topic/utils/layout.ts

add buttons were overlapping with edge labels, which was annoying
- 
-

touchup: increase spacing between layers

---

web/src/common/components/Layout.tsx
web/src/pages/index.page.tsx

- add demo to home page & clean up headers
-

Add demo to homepage

---

web/src/pages/index.page.tsx

- "about" kind of makes the first half of the sentence awkward until you read the second half. Hopefully this is better
-

docs(metadata): "communicate about" -> "discuss"

---

README.md
web/src/pages/index.page.tsx

woops, missed these spots in the last PR
- 
-

docs: "communicating about" -> "discussing"

---

web/public/examples/cars_going_too_fast_in_neighborhood.json
web/public/examples/world_hunger.json
web/src/modules/topic/components/Surface/TopicToolbar.tsx

- add cars too fast example from demo video
- update world hunger example from usage in blog
-

Add scores to world hunger ex

---

web/src/pages/about.page.tsx

Update about page per blog

---

.github/CODEOWNERS
web/src/modules/topic/components/Indicator/Indicator.tsx

- add codeowners
- remove dead code
-

Add codeowners

---

web/docs/state-management.md
web/src/common/components/Menu/Menu.tsx
web/src/common/errorHandling.ts
web/src/modules/topic/components/CriteriaTable/CriteriaTable.tsx
web/src/modules/topic/components/Diagram/Diagram.styles.tsx
web/src/modules/topic/components/Node/EditableNode.styles.tsx
web/src/modules/topic/components/Node/FlowNode.styles.tsx
web/src/modules/topic/components/Node/FlowNode.tsx
web/src/modules/topic/components/Node/NodeHandle.styles.tsx
web/src/modules/topic/components/Node/NodeHandle.tsx
web/src/modules/topic/components/Score/ScorePie.tsx
web/src/modules/topic/components/ScoreEdge/ScoreEdge.styles.tsx
web/src/modules/topic/components/ScoreEdge/ScoreEdge.tsx
web/src/modules/topic/components/Surface/TopicToolbar.tsx
web/src/modules/topic/store/actions.ts
web/src/modules/topic/store/createDeleteActions.ts
web/src/modules/topic/store/edgeHooks.ts
web/src/modules/topic/store/migrate.ts
web/src/modules/topic/store/nodeHooks.ts
web/src/modules/topic/store/store.ts
web/src/modules/topic/store/utilActions.ts
web/src/modules/topic/store/utils.ts
web/src/modules/topic/store/viewActions.ts
web/src/modules/topic/utils/claim.ts
web/src/modules/topic/utils/diagram.ts
web/src/modules/topic/utils/node.ts
web/tsconfig.json

- use the noUncheckedIndexedAccess tsconfig flag to have a little bit stricter typing
- see commit messages for rest, small-ish improvements
-

Set no unchecked index access

---

.github/workflows/ci.yml
CONTRIBUTING.md
commitlint.config.js

Closes #127 
- updated the CI process to check commit messages for correctness. 
- using conventional commits as the standard.

build: lint commits on pr

---

next.config.js
src/common/utils.ts
src/pages/api/panel.page.ts
src/web/common/trpc.ts

Fix prod base url

---

src/web/common/hooks.ts

fix: topics page infinitely loads if not logged in

---

src/common/reservedEndpointNames.ts
src/common/topic.ts
src/common/user.ts

touchup: reserve endpoint usernames/topic titles

---

src/web/topic/components/Score/Score.tsx
src/web/topic/hooks/flowHooks.ts
src/web/topic/hooks/topicHooks.ts

perf: don't re-render every viewport change

---

package-lock.json
src/pages/[username]/[topicTitle].page.tsx
src/web/common/components/Layout.tsx
src/web/topic/hooks/flowHooks.ts
src/web/topic/store/apiSyncerMiddleware.ts
src/web/topic/store/createDeleteActions.ts
src/web/topic/store/store.ts
src/web/topic/store/viewActions.ts
src/web/topic/utils/apiConversion.ts
src/web/topic/utils/diagram.ts

Misc touchups 2

---

src/web/topic/components/Surface/TopicToolbar.tsx

fix: download button hidden if not creator

---

docs/state-management.md
package-lock.json
package.json
src/api/routers/topic.ts
src/web/common/components/ContextMenu/DeleteEdgeMenuItem.tsx
src/web/common/components/ContextMenu/DeleteNodeMenuItem.tsx
src/web/topic/store/actions.ts
src/web/topic/store/createDeleteActions.ts
src/web/topic/store/nodeHooks.ts
src/web/topic/store/store.ts
src/web/topic/store/utils.ts
src/web/topic/store/viewActions.ts
src/web/topic/utils/diagram.ts

Perf all nodes always rerender

---

src/web/common/event.ts
src/web/topic/components/Diagram/Diagram.tsx
src/web/topic/hooks/flowHooks.ts
src/web/topic/store/loadActions.ts
src/web/topic/store/utilActions.ts

Center diagram after load

---

src/pages/api/auth/[...auth0].page.ts
src/web/topic/store/graphPartHooks.ts

Remove unnecessary auth0 query params

---

src/common/node.ts

touchup: uses spaces for new topic node

---

src/web/topic/components/Node/EditableNode.tsx
src/web/topic/store/store.ts

43 editing node text jumps cursor to end of input

---

src/web/topic/components/Diagram/Diagram.styles.tsx
src/web/topic/components/Diagram/Diagram.tsx
src/web/topic/components/Node/FlowNode.styles.tsx
src/web/topic/components/Node/FlowNode.tsx
src/web/topic/components/Node/NodeHandle.styles.tsx
src/web/topic/components/Node/NodeHandle.tsx
src/web/topic/components/ScoreEdge/ScoreEdge.styles.tsx
src/web/topic/components/ScoreEdge/ScoreEdge.tsx
src/web/topic/store/edgeHooks.ts
src/web/topic/store/graphPartHooks.ts

Dont make background nodes transparent

---

src/web/topic/components/Node/AddNodeButton.tsx
src/web/topic/components/Score/Score.styles.tsx
src/web/topic/components/Score/Score.tsx

Closes #163 
-
errors not displaying locally:

163 hovering score logs anchorel prop is invalid error

---

src/web/common/components/ContextMenu/ContextMenu.tsx
src/web/topic/components/Diagram/Diagram.tsx

Closes #38 
- Disabled browser context menu in the diagram
- Disable browser context menu in the custom context menu

feat: disable browser context menu in diagram

---

src/api/routers/topic.ts
src/db/migrations/20230905082933_add_username_to_topic_and_score/down.sql
src/db/migrations/20230905082933_add_username_to_topic_and_score/migration.sql
src/db/schema.prisma
src/web/topic/store/loadActions.ts

Add username f ks

---

scripts/seed.ts
src/api/routers/topic.ts
src/common/topic.ts
src/common/userScore.ts
src/db/migrations/20230905092640_set_username_data_on_topic_and_score/down.sql
src/db/migrations/20230905092640_set_username_data_on_topic_and_score/migration.sql
src/db/migrations/20230905103109_replace_userid_with_username/down.sql
src/db/migrations/20230905103109_replace_userid_with_username/migration.sql
src/db/schema.prisma
src/web/common/components/ContextMenu/DeleteEdgeMenuItem.tsx
src/web/common/components/ContextMenu/DeleteNodeMenuItem.tsx
src/web/topic/components/CriteriaTable/CriteriaTable.tsx
src/web/topic/components/Indicator/ClaimIndicator.tsx
src/web/topic/components/Node/EditableNode.tsx
src/web/topic/components/Node/FlowNode.tsx
src/web/topic/components/Score/Score.tsx
src/web/topic/components/Surface/TopicToolbar.tsx
src/web/topic/store/apiSyncerMiddleware.ts
src/web/topic/store/userHooks.ts
src/web/topic/utils/apiConversion.ts

Replace userid fks with username

---

scripts/seed.ts
src/api/routers/topic.ts
src/db/migrations/20230905142052_remove_userid_from_topic_and_score/down.sql
src/db/migrations/20230905142052_remove_userid_from_topic_and_score/migration.sql
src/db/schema.prisma
src/web/topic/store/loadActions.ts

Remove userid from topic score

---

src/pages/[username]/[topicTitle].page.tsx
src/pages/playground.page.tsx
src/web/topic/components/Indicator/EdgeIndicatorGroup.tsx
src/web/topic/components/Indicator/NodeIndicatorGroup.tsx
src/web/topic/components/Score/Score.stories.tsx
src/web/topic/components/Score/Score.tsx
src/web/topic/components/Score/ScorePie.tsx
src/web/topic/components/Surface/TopicToolbar.tsx
src/web/topic/store/actions.ts
src/web/topic/store/graphPartHooks.ts
src/web/topic/store/loadActions.ts
src/web/topic/store/migrate.ts
src/web/topic/store/scoreHooks.ts
src/web/topic/store/store.ts
src/web/topic/store/utilActions.ts
src/web/topic/store/viewActions.ts
src/web/topic/utils/apiConversion.ts
src/web/topic/utils/diagram.ts
src/web/topic/utils/edge.ts
src/web/view/components/Perspectives/Perspectives.tsx
src/web/view/store/store.ts

Partial for #191 
-
- second PR for viewing multiple users' scores at once

191 allow multiple users to score the same topic

---

src/api/auth.ts
src/api/context.ts
src/api/routers/user.ts
src/pages/api/auth/[...auth0].page.ts
src/pages/choose-username.page.tsx
src/web/common/hooks.ts
src/web/topic/components/TopicForm/TopicForm.tsx

Require email verification

---

src/web/topic/components/CriteriaTable/CriteriaTable.tsx

fix(table): no col id's warning

---

.vscode/extensions.json
.vscode/settings.json
CONTRIBUTING.md
docs/architecture-by-env.md
docs/data-flow.md
docs/database-schema.md
docs/vocabulary.md

Add architecture, schema, data flow diagrams

---

src/web/topic/store/apiSyncerMiddleware.ts

before this commit, topic data was only being saved if the client's browser had redux devtools installed.
this was an absurd issue, but ultimately zustand has a `setState` method, which we rely on because of our "no store actions" pattern, but the zustand middleware example only shows overriding the `set` method, so we only overrode that one.
the `set` method override would be sufficient if the client has redux devtools installed because zustand's devtools middleware invokes `set` when `setState` is called.
we definitely don't want to rely on this, so we just need to override `setState` as well, to ensure our middleware is always triggered.

fix: topic only saves if redux extension installed

---

.env.example
CONTRIBUTING.md

fix: can't run app locally without auth creds

---

.gitignore
CONTRIBUTING.md
docs/architecture-by-env.md
mock-auth/Dockerfile
mock-auth/index.ts
mock-auth/package-lock.json
mock-auth/package.json
mock-auth/tsconfig.json
package.json
scripts/mockAuthStart.sh
scripts/setupLocal.sh
scripts/update.sh

chore: set up mock-auth server for local dev

---

.env.example
src/web/common/event.ts
src/web/topic/components/Surface/MoreActionsDrawer.tsx
src/web/topic/components/Surface/TopicToolbar.tsx
src/web/topic/store/apiSyncerMiddleware.ts

indicate if diagram saving has failed

---

src/api/auth.ts
src/api/context.ts
src/api/routers/topic.ts
src/api/routers/user.ts
src/common/topic.ts
src/db/migrations/20231010141243_add_topic_visibility_column/down.sql
src/db/migrations/20231010141243_add_topic_visibility_column/migration.sql
src/db/schema.prisma
src/pages/[username].page.tsx
src/web/topic/components/Surface/TopicDrawer.styles.tsx
src/web/topic/components/Surface/TopicDrawer.tsx
src/web/topic/components/TopicForm/TopicForm.tsx
src/web/topic/components/TopicWorkspace/TopicWorkspace.tsx
src/web/topic/store/store.ts

212 private topics

---

.github/workflows/ci.yml
package-lock.json
package.json
scripts/setupTests.ts
src/api/auth.ts
src/api/context.ts
src/api/routers/topic.test.ts
src/api/routers/user.test.ts
src/api/routers/user.ts
vitest.config.ts

motivation: would be good to have extra confidence that private topics are treated with proper security

Add api tests

---

src/api/routers/topic.ts
src/pages/[username].page.tsx
src/web/topic/components/Node/EditableNode.styles.tsx
src/web/topic/components/Node/EditableNode.tsx
src/web/topic/store/createDeleteActions.ts

Small cleanups

---

scripts/dbStart.sh
scripts/mockAuthStart.sh
scripts/update.sh

touchup: handle shell script errors better

---

src/web/topic/components/Surface/TopicToolbar.tsx
src/web/topic/store/createDeleteActions.ts
src/web/topic/store/graphPartHooks.ts
src/web/topic/utils/diagram.ts

Closes #221 
What do you think about having a delete button as part of the node/edge? I hacked up a prototype to see what it would look like. I think it's more discoverable here than in the menu, as suggested in the linked issue. But totally understand if you think it's taking up valuable real estate.
- Added delete button to node/edge. (Is `Indicator` the right term for this? Wasn't sure what this was supposed to mean)
-

Add delete button to edges and nodes

---

src/common/edge.ts
src/common/node.ts
src/db/migrations/20231025221055_add_notes_to_graph_parts/down.sql
src/db/migrations/20231025221055_add_notes_to_graph_parts/migration.sql
src/db/schema.prisma
src/web/topic/components/Node/EditableNode.tsx
src/web/topic/components/Surface/GraphPartDetails.tsx
src/web/topic/components/Surface/TopicDetails.tsx
src/web/topic/components/Surface/TopicDrawer.tsx
src/web/topic/store/actions.ts
src/web/topic/utils/apiConversion.ts
src/web/topic/utils/diagram.ts

Add scratch notes per node edge

---

src/pages/[username].page.tsx
src/pages/[username]/[topicTitle].page.tsx
src/pages/[username]/[topicTitle]/settings.page.tsx
src/pages/about.page.tsx
src/web/topic/components/Edge/ScoreEdge.styles.tsx
src/web/topic/components/Edge/ScoreEdge.tsx
src/web/topic/components/Node/EditableNode.styles.tsx
src/web/topic/components/Node/EditableNode.tsx
src/web/topic/components/Surface/GraphPartDetails.tsx

Small improvements

---

src/web/topic/components/Diagram/Diagram.tsx
src/web/topic/components/Indicator/CriteriaTableIndicator.tsx
src/web/topic/components/Surface/TopicPane.styles.tsx
src/web/topic/components/Surface/TopicPane.tsx
src/web/topic/components/Surface/TopicViews.tsx
src/web/topic/components/TopicWorkspace/TopicWorkspace.tsx
src/web/topic/store/createDeleteActions.ts
src/web/topic/store/nodeHooks.ts

More small improvements

---

src/common/node.ts
src/web/topic/components/Diagram/Diagram.tsx
src/web/topic/components/Score/Score.tsx
src/web/topic/components/Score/ScoreButton.tsx
src/web/topic/utils/edge.ts
src/web/topic/utils/layout.ts
src/web/topic/utils/node.ts

Closes #84
Closes #25 
Closes #240 
- see commits
-

Even more small improvements

---

src/web/topic/components/Diagram/Diagram.tsx
src/web/topic/utils/edge.ts

Noticed that this would be nice

touchup: allow reconnecting claims

---

src/web/topic/utils/layout.ts

fix: partitions cause layout exception

---

src/common/edge.ts
src/common/node.ts
src/db/migrations/20231205141720_allow_edges_to_point_to_edges/down.sql
src/db/migrations/20231205141720_allow_edges_to_point_to_edges/migration.sql
src/db/migrations/20231206161732_add_explore_nodes/down.sql
src/db/migrations/20231206161732_add_explore_nodes/migration.sql
src/db/schema.prisma
src/pages/_app.styles.tsx
src/web/common/theme.ts
src/web/topic/components/CriteriaTable/CriteriaTable.tsx
src/web/topic/components/CriteriaTable/NodeCell.styles.tsx
src/web/topic/components/Diagram/Diagram.tsx
src/web/topic/components/Indicator/DetailsIndicator.tsx
src/web/topic/components/Node/AddNodeButton.tsx
src/web/topic/components/Node/AddNodeButtonGroup.tsx
src/web/topic/components/Node/EditableNode.styles.tsx
src/web/topic/components/Surface/DetailsClaimsSection.tsx
src/web/topic/components/Surface/DetailsExploreSection.tsx
src/web/topic/components/Surface/GraphPartDetails.tsx
src/web/topic/components/Surface/TopicPane.styles.tsx
src/web/topic/components/TopicWorkspace/TopicWorkspace.tsx
src/web/topic/store/createDeleteActions.ts
src/web/topic/store/graphPartHooks.ts
src/web/topic/store/utils.ts
src/web/topic/utils/apiConversion.ts
src/web/topic/utils/edge.ts
src/web/topic/utils/graph.ts
src/web/topic/utils/layout.ts
src/web/topic/utils/node.ts

Partially addresses #230 
- see commits
-

Add exploration nodes

---

src/web/topic/components/Diagram/ClaimTree.styles.tsx
src/web/topic/components/Diagram/ExploreDiagram.tsx
src/web/topic/components/Indicator/ClaimTreeIndicator.tsx
src/web/topic/components/Indicator/Indicator.tsx
src/web/topic/components/Surface/MoreActionsDrawer.tsx
src/web/topic/components/TopicPane/TopicPane.tsx
src/web/topic/components/TopicPane/TopicViews.tsx
src/web/topic/components/TopicWorkspace/TopicWorkspace.tsx
src/web/topic/store/createDeleteActions.ts
src/web/topic/store/store.ts
src/web/topic/store/utils.ts
src/web/topic/utils/diagram.ts
src/web/topic/utils/layout.ts
src/web/view/navigateStore.ts

Add explore diagram

---

src/web/topic/components/TopicPane/GraphPartDetails.tsx
src/web/topic/components/TopicPane/TopicDetails.tsx

fix: notes and description don't undo/redo

---

src/common/diagram.ts
src/common/node.ts
src/web/topic/components/Diagram/Diagram.tsx
src/web/topic/components/Node/FlowNode.tsx
src/web/topic/components/Surface/MoreActionsDrawer.tsx
src/web/topic/components/TopicPane/GraphPartDetails.tsx
src/web/topic/store/utils.ts
src/web/topic/utils/diagram.ts

Optional show explore nodes across diagrams

---

src/pages/index.page.tsx
src/pages/index.style.tsx
src/web/common/components/SubscribeForm/SubscribeForm.tsx

- adds blog and session subscribe buttons
-

feat(home): add blog and session subscribe buttons

---

src/common/edge.ts
src/db/migrations/20240104115953_add_accomplishes_edge_type/down.sql
src/db/migrations/20240104115953_add_accomplishes_edge_type/migration.sql
src/db/schema.prisma
src/web/topic/components/Node/AddNodeButtonGroup.tsx
src/web/topic/store/createDeleteActions.ts
src/web/topic/utils/edge.ts

Add accomplishes edge type

---

src/db/migrations/20240108134835_add_case_insensitive_collation/down.sql
src/db/migrations/20240108134835_add_case_insensitive_collation/migration.sql
src/db/migrations/20240108135053_set_topic_title_case_insensitive/down.sql
src/db/migrations/20240108135053_set_topic_title_case_insensitive/migration.sql
src/db/migrations/20240108140848_set_username_case_insensitive/down.sql
src/db/migrations/20240108140848_set_username_case_insensitive/migration.sql
src/db/schema.prisma
src/pages/index.page.tsx

Closes #272 
- also added link to explain discourse sessions
-

Make topic case insensitive

---

src/pages/index.page.tsx
src/web/common/urls.ts

touchup(home): add mention of youtube channel

---

src/pages/[username]/[topicTitle].page.tsx
src/pages/playground.page.tsx
src/web/topic/components/Surface/TopicToolbar.tsx
src/web/view/navigateStore.ts

required upgrading next so that useSearchParams does not include path params https://github.com/vercel/next.js/pull/55280
Closes #214 
-
-

feat: add navigation params to URL

---

src/common/node.ts
src/db/migrations/20240122114058_add_benefits_detriments/down.sql
src/db/migrations/20240122114058_add_benefits_detriments/migration.sql
src/db/schema.prisma
src/web/common/theme.ts
src/web/topic/components/Diagram/Diagram.tsx
src/web/topic/utils/edge.ts
src/web/topic/utils/layout.ts
src/web/topic/utils/node.ts

Closes #306 
-
- includes adding logic to calculate partition for these node types, since
they should sometimes be above criteria and sometimes below.

306 benefit and detriment node types

---

src/common/errorHandling.ts
src/web/topic/components/CriteriaTable/CriteriaTable.tsx
src/web/topic/components/CriteriaTable/SolutionTotalCell.tsx
src/web/topic/components/CriteriaTable/TotalsHeaderCell.tsx
src/web/topic/components/Indicator/QuestionIndicator.tsx
src/web/topic/store/scoreHooks.ts
src/web/topic/utils/edge.ts
src/web/topic/utils/score.ts

205 calculate weighted solution totals for table

---

src/web/topic/components/Node/EditableNode.tsx
src/web/topic/utils/node.ts

Touchup custom node

---

src/common/node.ts
src/db/migrations/20240130162820_add_cause_node/down.sql
src/db/migrations/20240130162820_add_cause_node/migration.sql
src/db/schema.prisma
src/web/common/theme.ts
src/web/topic/components/Diagram/Diagram.tsx
src/web/topic/utils/edge.ts
src/web/topic/utils/layout.ts
src/web/topic/utils/node.ts

this is based on feedback in the first discourse session.
seems nice to distinguish causes from main problems.
causes are good to think about addressing, but only for the purpose
of solving main problems.
-
-

Add cause node

---

docs/diagram-rendering.md
src/web/common/event.ts
src/web/topic/components/Diagram/Diagram.tsx
src/web/topic/components/TopicPane/GraphPartDetails.tsx
src/web/topic/components/TopicPane/TopicViews.tsx
src/web/topic/store/nodeHooks.ts
src/web/topic/store/store.ts
src/web/topic/utils/diagram.ts
src/web/topic/utils/edge.ts
src/web/topic/utils/graph.ts
src/web/view/components/FilterOptions/FilterOptions.tsx
src/web/view/components/Perspectives/Perspectives.tsx
src/web/view/navigateStore.ts
src/web/view/utils/filter.ts

Closes #317 
-
- More filters to come, but this adds a few basic ones

Add diagram filters

---

src/web/topic/hooks/diagramHooks.ts
src/web/topic/store/store.ts
src/web/topic/utils/graph.ts
src/web/topic/utils/layout.ts
src/web/view/components/FilterOptions/FilterOptions.tsx
src/web/view/navigateStore.ts
src/web/view/utils/filter.ts

also removed partitioning from contextual nodes, because it seems like it makes sense for them to be right next to the node they're providing context to.
-
-

feat: add contextual nodes option

---

package-lock.json
package.json
src/pages/_app.page.tsx
src/web/topic/store/createDeleteActions.ts
src/web/topic/store/nodeHooks.ts
src/web/view/components/FilterOptions/FilterOptions.tsx
src/web/view/utils/filter.ts

see commit messages:
- fix/touchup a bunch of misc things
- add a few new filters
-

Add solution filter

---

src/web/topic/hooks/flowHooks.ts
src/web/topic/store/utilActions.ts
src/web/view/utils/filter.ts

Some fixes

---

README.md
src/web/common/components/ContextMenu/AddNodeMenuItem.tsx
src/web/common/components/ContextMenu/ContextMenu.tsx
src/web/common/store/contextMenuActions.ts
src/web/topic/components/Diagram/Diagram.tsx
src/web/topic/store/createDeleteActions.ts

should be particularly useful for questions that aren't targeting a specific parent.
Closes #296 
-
-

feat: add node without parent

---

src/web/common/components/ContextMenu/ContextMenu.tsx

touchup: always have at least 1 context menu item

---

src/api/routers/topic.test.ts
src/api/routers/topic.ts
src/common/topic.ts
src/db/migrations/20240215171355_add_allow_anyone_to_edit/down.sql
src/db/migrations/20240215171355_add_allow_anyone_to_edit/migration.sql
src/db/schema.prisma
src/web/topic/components/TopicForm/TopicForm.tsx
src/web/topic/components/TopicPane/TopicDetails.tsx
src/web/topic/store/userHooks.ts

Allow others to edit

---

package-lock.json
package.json
src/web/topic/components/Diagram/Diagram.tsx
src/web/topic/components/Diagram/externalFlowStore.ts
src/web/topic/components/Surface/MoreActionsDrawer.tsx
src/web/view/navigateStore.ts

Closes #332 
-
- requested from discourse session

feat: take screenshot of diagram

---

CONTRIBUTING.md

not actually sure if it's required but I don't think windows normally comes with bash.
-
-

docs: mention wsl for running project on windows

---

docs-site/.eslintrc.json
docs-site/.npmrc
docs-site/next.config.js
docs-site/package-lock.json
docs-site/package.json

add eslint config and packages
remove esm usage from next config
-
-

fix(docs-site): build errors

---

docs-site/.eslintrc.json
docs-site/README.md
docs-site/package.json
docs-site/theme.config.tsx

Fix docs site broken logo

---

src/common/edge.ts
src/db/migrations/20240225160103_add_mentions_relation/down.sql
src/db/migrations/20240225160103_add_mentions_relation/migration.sql
src/db/schema.prisma
src/web/topic/store/nodeHooks.ts
src/web/topic/utils/edge.ts
src/web/view/components/FilterOptions/FilterOptions.tsx
src/web/view/utils/filter.ts

Allow explore trees

---

docs-site/pages/_meta.json
docs-site/pages/contributing.mdx
docs-site/pages/discourse-sessions.mdx
docs-site/pages/index.mdx
src/pages/index.page.tsx
src/web/common/components/Layout.tsx

Fill out discourse docs

---

src/common/topic.ts
src/web/topic/components/TopicForm/TopicForm.tsx

touchup: default topic visibility to private

---

docs-site/pages/_meta.json
docs-site/pages/features.mdx
docs-site/pages/features/_meta.json
docs-site/pages/features/views-and-filters.mdx
docs-site/pages/getting-started.mdx
docs-site/pages/getting-started/_meta.json
docs-site/pages/getting-started/core-ideas.mdx
docs-site/pages/getting-started/diagramming-basics.mdx
docs-site/pages/getting-started/your-first-topic.mdx
docs-site/pages/index.mdx

- finish getting started docs
-

docs(docs-site): fill out core ideas

---

src/web/common/components/Form/NodeSelect.tsx
src/web/common/components/Form/Select.tsx
src/web/common/components/Form/Switch.tsx
src/web/view/components/FilterOptions/FilterOptions.tsx
src/web/view/components/FilterOptions/ShowSecondaryNeighborsLabel.tsx

Refactor filter options

---

src/web/topic/components/CriteriaTable/CriteriaTable.tsx
src/web/topic/components/TopicPane/TopicViews.tsx
src/web/topic/store/nodeGetters.ts
src/web/view/components/FilterOptions/FilterOptions.tsx
src/web/view/navigateStore.ts
src/web/view/utils/filter.ts

- should be more convenient than using the default material-react-table filter UI
-

Use tradeoff filter for criteria table

---

src/web/common/components/Form/Select.tsx
src/web/topic/components/CriteriaTable/CriteriaTable.tsx
src/web/topic/components/Indicator/QuestionIndicator.tsx
src/web/topic/store/scoreGetters.ts
src/web/topic/store/scoreHooks.ts
src/web/topic/store/store.ts
src/web/view/components/FilterOptions/FilterOptions.tsx
src/web/view/navigateStore.ts
src/web/view/utils/filter.ts

Add only scored nodes filter

---

docs-site/pages/features/views-and-filters.mdx

docs(docs-site): add some filtering descriptions

---

src/common/edge.ts
src/common/node.ts
src/db/migrations/20240317162832_add_obstacle_node/down.sql
src/db/migrations/20240317162832_add_obstacle_node/migration.sql
src/db/schema.prisma
src/web/common/theme.ts
src/web/topic/components/Diagram/Diagram.tsx
src/web/topic/utils/edge.ts
src/web/topic/utils/layout.ts
src/web/topic/utils/node.ts
src/web/view/utils/filter.ts

Add obstacle node

---

src/pages/api/auth/[...auth0].page.ts
src/web/common/components/Layout.tsx
src/web/common/components/NumberInput/NumberInput.tsx
src/web/common/components/UserDrawer/UserDrawer.tsx
src/web/topic/components/Surface/MoreActionsDrawer.tsx
src/web/topic/hooks/diagramHooks.ts
src/web/topic/utils/layout.ts
src/web/view/actionConfigStore.ts
src/web/view/components/FilterOptions/FilterOptions.tsx

Add thoroughness option

---

src/web/view/components/FilterOptions/FilterOptions.tsx
src/web/view/utils/filter.ts

touchup: add solution detail to problem filter

---

src/web/topic/utils/edge.ts

also reorder add node buttons so that answer is left of fact/source
-
-

touchup: allow chaining facts

---

src/web/view/utils/filter.ts

not quite sure what to do about chaining facts under a question, since it seems like those would want to chain downwards. can keep that in mind.
-
-

touchup: add fact chaining to sources filter

---

src/common/edge.ts
src/common/node.ts
src/db/migrations/20240319163208_add_subproblemof_relation/down.sql
src/db/migrations/20240319163208_add_subproblemof_relation/migration.sql
src/db/schema.prisma
src/web/topic/utils/edge.ts

Add subproblem of relation

---

src/web/view/components/FilterOptions/FilterOptions.tsx
src/web/view/utils/filter.ts

also refactor 4 show-node switches into multi-select
-
-

touchup: add subproblems to problem filter details

---

src/pages/api/auth/[...auth0].page.ts

chore: test deployed netlify code param passing

---

src/web/topic/components/TopicWorkspace/TopicWorkspace.tsx
src/web/topic/store/edgeHooks.ts

Fix table scroll

---

src/pages/[username]/[topicTitle].page.tsx
src/pages/playground.page.tsx
src/web/common/event.ts
src/web/topic/components/Diagram/Diagram.tsx
src/web/topic/components/Surface/TopicToolbar.tsx
src/web/topic/store/loadActions.ts
src/web/topic/store/utilActions.ts
src/web/view/navigateStore.ts

- see explanations in commit messages
-

Undo redo navigation

---

src/web/topic/utils/edge.ts
src/web/view/components/Filter/GeneralFilters.tsx

Improve solution negative relations

---

netlify.toml
package-lock.json
package.json

Fix netlify deploy

---

src/web/topic/components/TopicPane/FactDetails.tsx
src/web/topic/components/TopicPane/SourceDetails.tsx
src/web/topic/utils/edge.ts

Add solution addresses detriment

---

package-lock.json
package.json
src/api/routers/_app.ts
src/api/routers/topic.ts
src/api/routers/view.ts
src/common/view.ts
src/db/migrations/20240511210044_add_views_table/down.sql
src/db/migrations/20240511210044_add_views_table/migration.sql
src/db/schema.prisma
src/pages/[username]/[topicTitle].page.tsx
src/pages/playground.page.tsx
src/web/common/components/Layout.tsx
src/web/common/event.ts
src/web/topic/components/Surface/MoreActionsDrawer.tsx
src/web/topic/components/TopicForm/TopicForm.tsx
src/web/topic/components/TopicPane/QuickViewForm.tsx
src/web/topic/components/TopicPane/QuickViewSection.tsx
src/web/topic/components/TopicPane/TopicViews.tsx
src/web/topic/store/loadActions.ts
src/web/topic/store/store.ts
src/web/topic/store/utilActions.ts
src/web/topic/utils/edge.ts
src/web/view/currentViewStore/store.ts
src/web/view/currentViewStore/triggerEventMiddleware.ts
src/web/view/quickViewStore/apiSyncerMiddleware.ts
src/web/view/quickViewStore/store.ts

Recommended views

---

docs-site/pages/getting-started/your-first-topic.mdx
src/web/common/components/Form/NodeSelect.tsx
src/web/common/components/Form/Select.tsx
src/web/topic/components/TopicPane/DetailsResearchSection.tsx
src/web/topic/components/TopicPane/SourceDetails.tsx
src/web/topic/store/createDeleteActions.ts
src/web/topic/store/graphPartHooks.ts
src/web/topic/store/nodeTypeHooks.ts
src/web/topic/utils/graph.ts
src/web/view/components/Filter/GeneralFilters.tsx
src/web/view/currentViewStore/store.ts
src/web/view/utils/generalFilter.ts

Misc touchups 3

---

README.md
docs-site/pages/getting-started/core-ideas.mdx

fix(docs): incorrect links to specific views

---

src/api/routers/view.ts
src/web/view/quickViewStore/apiSyncerMiddleware.ts
src/web/view/quickViewStore/store.ts

Fix upload doesnt maintain view topic

---

src/api/routers/view.test.ts

to ensure proper authorizations
-
-

test: add view router tests

---

src/pages/[username]/[topicTitle].page.tsx
src/pages/playground.page.tsx
src/web/comment/components/Comment.tsx
src/web/comment/store/commentStore.ts
src/web/common/store/utils.ts
src/web/topic/loadStores.ts
src/web/view/quickViewStore/store.ts

Add link to comment

---

src/api/routers/topic.ts

fix: can't delete graph parts if score is orphaned

---

mock-auth/index.ts
scripts/generateMigration.ts
scripts/rollbackMigration.ts
scripts/seed.ts
scripts/setupTests.ts
src/api/notifications/commentCreated.test.ts
src/api/routers/comment.test.ts
src/api/routers/topic.test.ts
src/api/routers/user.test.ts
src/api/routers/user.ts
src/api/routers/view.test.ts
src/common/user.ts
src/db/migrations/20240619160638_add_email_to_user/down.sql
src/db/migrations/20240619160638_add_email_to_user/migration.sql
src/db/schema.prisma
src/pages/choose-username.page.tsx

Add email to user

---

package-lock.json
package.json

particularly useful for type narrowing
see video for explanation https://www.youtube.com/watch?v=vwUIZyOP8_4
-
-

chore: upgrade typescript to 5.5

---

src/web/topic/utils/layout.ts

e.g. https://ameliorate.app/keyserj/use-cases is hard to read
-
-

touchup: increase spacing between node islands

---

src/web/topic/components/Indicator/StatusIndicators.tsx
src/web/topic/components/Node/EditableNode.tsx
src/web/topic/components/Surface/MoreActionsDrawer.tsx
src/web/view/userConfigStore.ts

Select node switch to details tab

---

.env.example
next.config.js
package-lock.json
package.json
sentry.client.config.ts
src/api/context.ts
src/api/trpc.ts
src/db/schema.prisma
src/instrumentation.page.ts
src/pages/_error.page.tsx
src/web/common/components/Error/Error.tsx
src/web/common/hooks.ts

Add sentry monitoring

---

src/web/home/Headline.tsx

touchup: improve headline wording

---

src/web/home/Card.tsx
src/web/topic/components/Diagram/Diagram.tsx

Home page carousel accessibility

---

src/web/topic/components/Score/Score.tsx
src/web/topic/components/TopicWorkspace/TopicWorkspace.tsx
src/web/topic/store/utilActions.ts
src/web/topic/utils/hotkeys.ts
src/web/topic/utils/score.ts
src/web/view/actionConfigStore.ts
src/web/view/currentViewStore/store.ts
src/web/view/perspectiveStore.ts

touchup: allow scoring with keyboard

---

src/web/topic/components/CriteriaTable/CriteriaTable.styles.tsx
src/web/topic/components/TopicWorkspace/TopicWorkspace.tsx

touchup: center workspace loading icon

---

docs-site/.eslintrc.json
docs-site/globals.css
docs-site/package-lock.json
docs-site/package.json
docs-site/pages/_app.tsx
docs-site/postcss.config.cjs
docs-site/postcss.config.js
docs-site/tailwind.config.js
docs-site/theme.config.tsx
src/web/common/components/Layout.tsx

Touchup alpha positioning

---

src/web/home/CoreIdeasSection.tsx
src/web/home/Headline.tsx

touchup: improve headline phrasing

---

README.md
src/pages/index.page.tsx

touchup: add new phrasings to readme and metadata

---

src/pages/api/auth/[...auth0].page.ts
src/pages/choose-username.page.tsx
src/pages/new.page.tsx
src/web/topic/components/TopicWorkspace/MoreActionsDrawer.tsx

Fix start building return to

---

src/web/topic/store/createDeleteActions.ts
src/web/topic/utils/edge.ts

Component components

---

src/web/topic/components/Node/AddNodeButton.tsx
src/web/topic/components/Node/FlowNode.tsx
src/web/topic/components/TopicPane/DetailsClaimsSection.tsx
src/web/topic/components/TopicPane/DetailsResearchSection.tsx
src/web/topic/components/TopicPane/FactDetails.tsx
src/web/topic/components/TopicPane/QuestionDetails.tsx
src/web/topic/components/TopicPane/SourceDetails.tsx
src/web/topic/components/TopicWorkspace/WorkspaceToolbar.tsx
src/web/topic/store/userHooks.ts

Apply readonly to all front edit checks

---

src/web/topic/components/TopicForm/TopicForm.tsx

touchup: use neutral color for cancel

---

design-docs/tutorial-paths.md
src/pages/_app.page.tsx
src/web/topic/components/NodeTypeText/NodeTypeText.tsx
src/web/topic/components/TopicWorkspace/HelpMenu.tsx
src/web/topic/components/TopicWorkspace/WorkspaceToolbar.tsx
src/web/topic/utils/edge.ts
src/web/tour/StepContent.tsx
src/web/tour/steps/breakdown.tsx
src/web/tour/steps/diagramBasics.tsx
src/web/tour/steps/welcome.tsx
src/web/tour/tour.ts
src/web/view/components/Filter/ShowSecondaryNeighborsLabel.tsx
src/web/view/quickViewStore/store.ts

Tutorial breaking down problem

---

src/web/topic/components/TopicWorkspace/HelpMenu.tsx
src/web/topic/components/TopicWorkspace/MoreActionsDrawer.tsx
src/web/topic/hooks/diagramHooks.ts
src/web/topic/utils/layout.ts
src/web/tour/tour.ts
src/web/tour/tourStore.ts
src/web/tour/tourUtils.ts
src/web/view/currentViewStore/layout.ts
src/web/view/currentViewStore/store.ts

Track tutorial progress

---

src/web/topic/components/TopicWorkspace/HelpMenu.tsx
src/web/tour/steps/addingNuance.tsx
src/web/tour/steps/breakdown.tsx
src/web/tour/tour.ts
src/web/tour/tourUtils.ts

feat: add nuance tutorial

---

src/pages/index.page.tsx
src/web/common/event.ts
src/web/topic/components/CriteriaTable/TotalsHeaderCell.tsx
src/web/topic/components/Diagram/Diagram.tsx
src/web/topic/components/TopicWorkspace/HelpMenu.tsx
src/web/tour/steps/addingNuance.tsx
src/web/tour/steps/evaluatingTradeoffs.tsx
src/web/tour/tour.ts
src/web/tour/tourUtils.ts
src/web/view/currentViewStore/layout.ts

Add table tutorial

---

src/web/view/quickViewStore/store.ts

the only reason for the `deepIsEqual` check was to prevent immediate deselection, but using a variable to track if we just selected seems slightly less problematic.
-
-

fix: view is deselected right after selecting

---

src/web/topic/components/TopicWorkspace/HelpMenu.tsx
src/web/tour/steps/buildingViews.tsx
src/web/tour/steps/evaluatingTradeoffs.tsx
src/web/tour/tour.ts
src/web/tour/tourUtils.ts

feat: add 'building views' tutorial

---

design-docs/tutorial-paths.md
src/web/topic/components/TopicWorkspace/HelpMenu.tsx
src/web/topic/components/TopicWorkspace/TourHelper.tsx
src/web/tour/steps/addingNuance.tsx
src/web/tour/steps/evaluatingTradeoffs.tsx
src/web/tour/steps/navigatingTopic.tsx
src/web/tour/steps/readingDiagram.tsx
src/web/tour/steps/welcome.tsx
src/web/tour/tour.ts
src/web/tour/tourStore.ts
src/web/tour/tourUtils.ts

Closes #419 
-
- still would like to automatically start:
- "diagram basics" if went through viewer tutorial but now have edit access
- "reading a diagram" if went through viewer tutorial from the criteria table side
- "evaluating tradeoffs" if went through viewer tutorial from the diagram side

Reading a diagram tutorial

---

README.md
src/pages/index.page.tsx
src/web/home/Headline.tsx
tailwind.config.js

Improve wording homepage

---

README.md
docs-site/pages/getting-started.mdx
package-lock.json
src/pages/_app.page.tsx
src/pages/index.page.tsx
src/web/home/Headline.tsx
src/web/topic/components/TopicWorkspace/HelpMenu.tsx
src/web/tutorial/steps/breakdown.tsx
src/web/tutorial/steps/readingDiagram.tsx
src/web/tutorial/steps/welcome.tsx

Anthony feedback

---

docs-site/pages/_meta.json
docs-site/pages/diagramming-choices.mdx

-
- inspired by recent discourse session

docs(diagram-choices): discuss solution variations

---

docs-site/pages/getting-started/core-ideas.mdx
docs-site/pages/getting-started/your-first-topic.mdx
src/web/common/urls.ts
src/web/home/CoreIdeasSection.tsx
src/web/home/Footer.tsx
src/web/topic/components/CriteriaTable/EdgeCell.tsx
src/web/tutorial/steps/addingNuance.tsx
src/web/tutorial/steps/breakdown.tsx
src/web/tutorial/steps/buildingViews.tsx
src/web/tutorial/steps/diagramBasics.tsx
src/web/tutorial/steps/evaluatingTradeoffs.tsx
src/web/tutorial/steps/navigatingTopic.tsx
src/web/tutorial/steps/readingDiagram.tsx
src/web/view/quickViewStore/store.ts

Misc touchups 8

---

src/web/topic/components/CriteriaTable/CriteriaTable.tsx

fix(table): criteria appended after totals column

---

README.md
src/pages/index.page.tsx
src/web/home/Headline.tsx

not sure if this is best but we'll see how it feels.
main motivation is to distinguish that Ameliorate is not intended for all problems, like math problems.
-
-

touchup: use "debatable" wording for hook

---

src/pages/[username]/[topicTitle].page.tsx
src/pages/_app.page.tsx
src/pages/index.page.tsx
src/pages/playground.page.tsx

touchup: clean up open graph tags

---

sentry.client.config.ts
src/web/topic/components/TopicWorkspace/MoreActionsDrawer.tsx
src/web/topic/hooks/diagramHooks.ts
src/web/topic/utils/layout.ts
src/web/view/currentViewStore/layout.ts
src/web/view/currentViewStore/store.ts

Try to keep same layer nodes closer together

---

src/web/home/Headline.tsx

touchup: add demo link to homepage

---

src/db/dataMigrations/20240926155659_rename_structure_to_breakdown.ts

fix: data migration timeout

---

src/pages/_app.page.tsx
src/web/common/patches/fixGoogleTranslateIssue.ts

fix: google translate breaks tutorial

---

src/web/topic/components/TopicWorkspace/TopicWorkspace.tsx
src/web/topic/store/graphPartHooks.ts
src/web/topic/utils/hotkeys.ts
src/web/view/currentViewStore/store.ts

Refactor getselected instead of getselectedid

---

docs-site/package-lock.json
docs-site/package.json
docs-site/pages/_app.tsx
package-lock.json
package.json
src/pages/_app.page.tsx

feat: add plausible analytics

---

docs-site/pages/_meta.json
docs-site/pages/faq.mdx

docs: add FAQs

---

.npmrc
package-lock.json
package.json
src/web/common/theme.ts
src/web/view/components/Perspectives/Perspectives.tsx
tailwind.config.js

New color theme

---

docs-site/pages/index.mdx
src/web/home/Footer.tsx
src/web/home/Headline.tsx

Add vision to landing page

---

src/web/topic/components/Node/EditableNode.styles.tsx

fix: readonly node can't scroll

---

src/web/topic/components/CriteriaTable/EdgeCell.tsx
src/web/topic/components/Edge/ScoreEdge.tsx
src/web/topic/components/Indicator/CommonIndicators.tsx
src/web/topic/components/Indicator/ContextIndicator.tsx
src/web/topic/components/Indicator/CriteriaTableIndicator.tsx
src/web/topic/components/Indicator/DetailsIndicator.tsx
src/web/topic/components/Indicator/ForceShownIndicator.tsx
src/web/topic/components/Indicator/Indicator.tsx
src/web/topic/components/Indicator/JustificationTreeIndicator.tsx
src/web/topic/components/Node/EditableNode.tsx
src/web/topic/components/TopicWorkspace/MoreActionsDrawer.tsx
src/web/topic/store/partContextHooks.ts
src/web/topic/utils/partContext.ts
src/web/view/currentViewStore/filter.ts
src/web/view/currentViewStore/store.ts
src/web/view/utils/contextFilters.ts
src/web/view/utils/diagramFilter.ts

View context button

---

src/web/common/theme.ts

cause: darken
detriment: brighten
solution: saturate
benefit: brighten
-
-

touchup: add more contrast between some colors

---

design-docs/state-management.md
src/web/comment/store/draftStore.ts

Update store docs

---

src/web/topic/components/CriteriaTable/CriteriaTable.tsx
src/web/topic/components/TopicWorkspace/MoreActionsDrawer.tsx
src/web/topic/store/partContextHooks.ts
src/web/topic/store/store.ts
src/web/topic/utils/edge.ts
src/web/view/components/Filter/InformationFilters.tsx
src/web/view/components/Filter/StandardFilter.tsx
src/web/view/currentViewStore/filter.ts
src/web/view/currentViewStore/store.ts
src/web/view/utils/contextFilters.ts
src/web/view/utils/infoFilter.ts
src/web/view/utils/miscDiagramFilters.ts

Allow hiding problem criterion solution edges

---

docs-site/next-sitemap.config.js
docs-site/package-lock.json
docs-site/package.json
docs-site/public/sitemap.xml
public/robots.txt
public/sitemap.xml
src/api/topic/topic.ts
src/common/comment.ts
src/common/topic.ts
src/pages/sitemap-generated.xml.page.ts
src/pages/sitemap-generated.xml.test.ts

includes:
- docs-site sitemap, generated at build time
- root site sitemap, generated at request time via public topics
- sitemap index, pointing to these
- robots.txt pointing to the sitemap index
Closes #550 
-
-

chore: add sitemap and robots.txt

---

src/web/common/components/Form/NumberInput.tsx
src/web/topic/store/store.ts
src/web/topic/utils/node.ts
src/web/view/components/Filter/StandardFilter.tsx
src/web/view/currentViewStore/filter.ts
src/web/view/utils/infoFilter.ts

High level layers

---

src/pages/_app.page.tsx
src/web/tutorial/tutorialStore.ts

seems useful to know if people are going through the tutorials
-
-

touchup: track tutorial usage via plausible

---

src/web/topic/utils/layout.ts

reproduce by opening the tutorial.
-
-

fix: header cut off (still)

---

src/web/topic/components/Diagram/Diagram.tsx
src/web/topic/components/Node/EditableNode.styles.tsx
src/web/topic/utils/layout.ts

Misc touchups 12

---

src/web/home/Headline.tsx

looks a bit cleaner now, and layout is different

touchup: bring headline image up to date

---

docs-site/public/sitemap.xml
src/web/topic/components/TopicPane/TopicDetails.tsx

Fix long topic title cut off

---

src/web/common/components/UserDrawer/UserDrawer.tsx
src/web/home/ExamplesSection.tsx

Misc touchups 13

---

docs-site/app/diagramming-choices/page.mdx
docs-site/public/sitemap.xml
package-lock.json
package.json
scripts/setupTests.ts
src/web/topic/utils/graph.test.ts
src/web/topic/utils/graph.ts

Fix circular dependency infinite recursion

---

package-lock.json
public/robots.txt
src/api/routers/topic.ts
src/common/edge.ts
src/common/node.ts
src/web/topic/components/TopicPane/TopicDetails.tsx
src/web/topic/store/actions.ts
src/web/topic/store/createDeleteActions.ts

Misc touchups 14

---

src/web/common/components/ContextMenu/DeleteEdgeMenuItem.tsx

since we're allowing multiple justification parents (for experimentation), we might as well also allow deleting justification edges now.
-
-

touchup: allow deleting justification edges

---

src/web/topic/components/Node/EditableNode.styles.tsx
src/web/topic/components/Node/EditableNode.tsx
src/web/topic/components/Node/NodeTextArea.tsx
src/web/topic/store/actions.ts

Text cut off in nodes

---

src/web/comment/store/apiSyncerMiddleware.ts
src/web/common/components/Error/apiSyncerError.tsx
src/web/common/components/InfoDialog/InfoDialog.tsx
src/web/common/components/InfoDialog/infoDialogStore.ts
src/web/common/components/InfoDialog/infoEvents.ts
src/web/common/event.ts
src/web/topic/components/Node/NodeTextArea.tsx
src/web/topic/components/TopicWorkspace/ContentFooter.tsx
src/web/topic/components/TopicWorkspace/TopicWorkspace.tsx
src/web/topic/store/actions.ts
src/web/topic/store/apiSyncerMiddleware.ts
src/web/view/quickViewStore/apiSyncerMiddleware.ts

Add info dialog

---

src/web/common/components/InfoDialog/InfoDialog.tsx
src/web/topic/components/Node/NodeTextArea.tsx

Closes #740 
Added arrow functionality . 
Added back the older comments
Further comments have been added for better readability
Added appropriate colors .
Since we cannot move the anchor while the dialog box is opened , I am unable to reach a case where the popper would appear on the left or right . But for the top and bottom its works way better than the last commit  .

Arrow it 2

---

src/web/topic/components/TopicPane/TopicDetails.tsx

Closes #736
Created a new object that just maps the camel case value to the start case . 
No additional changes were made whatsoever .

feat(input): use start case for watch dropdown values

---

src/api/notifications/commentCreated.ts
src/common/comment.ts
src/common/diagramPart.ts
src/common/topic.ts
src/common/utils.ts
src/pages/notifications.page.tsx
src/web/comment/components/Comment.tsx
src/web/common/components/ContextMenu/ContextMenu.tsx
src/web/common/components/ContextMenu/CopyLinkToPart.tsx
src/web/common/store/ephemeralStore.ts
src/web/common/trpc.ts
src/web/topic/components/Diagram/Diagram.tsx
src/web/topic/components/Node/NodeTextArea.tsx
src/web/topic/diagramStore/graphPartHooks.ts
src/web/topic/hooks/flowHooks.ts
src/web/topic/loadStores.ts
src/web/topic/topicStore/store.ts
src/web/topic/utils/topic.ts
src/web/view/quickViewStore/store.ts

Closes #608
Closes #760
- also fixed some minor bugs, see commit messages
-

Share view with node selected

---

src/web/common/components/Header/Logo.tsx
src/web/common/components/SiteDrawer/SiteDrawer.tsx
src/web/topic/components/Node/EditableNode.tsx

Misc touchups 18

---

src/web/topic/components/Diagram/Diagram.tsx

didn't seem like the extent of blur was necessary, and sometimes it'd be hard to even find blurred edges for changing selection.
-
-

touchup: reduce blur on selection

---

.prettierignore
examples/visible_act.json
package-lock.json
package.json
src/api/README.md
src/api/routers/__snapshots__/topicAI.getPromptData.json
src/api/routers/_app.ts
src/api/routers/topic.ts
src/api/routers/topicAI.test.ts
src/api/routers/topicAI.ts
src/api/routers/view.ts
src/api/topicAI.ts
src/common/edge.ts
src/common/node.ts
src/common/topic.ts
src/web/topic/components/Node/AddNodeButtonGroup.tsx
src/web/topic/components/TopicForm/TopicForm.tsx
src/web/topic/loadStores.ts
src/web/topic/utils/graph.ts

Api for llm

---

src/common/errorHandling.ts
src/web/topic/components/TopicWorkspace/MoreActionsDrawer.tsx
src/web/topic/loadStores.ts

motivated because someone got an error during upload, apparently it didn't have the right version number, but it's hard to know if it's because they uploaded their own invalid file, or if a legitimately downloaded file failed to process for some reason.
-
-

chore: log file text if upload errors
