amelioro/ameliorate

web/src/common/theme.ts
web/src/modules/topic/components/CriteriaIndicator/CriteriaIndicator.tsx
web/src/modules/topic/components/Diagram/Diagram.tsx
web/src/modules/topic/components/EditableNode/EditableNode.styles.tsx
web/src/modules/topic/components/EditableNode/EditableNode.tsx
web/src/modules/topic/components/Indicator/Indicator.styles.tsx
web/src/modules/topic/components/Indicator/Indicator.tsx
web/src/modules/topic/components/ScoreDial/ScoreDial.tsx
web/src/modules/topic/components/TopicToolbar/TopicToolbar.tsx
web/src/modules/topic/store/actions.ts
web/src/modules/topic/store/migrate.ts
web/src/modules/topic/store/nodeHooks.ts
web/src/modules/topic/store/store.ts
web/src/modules/topic/utils/claim.ts
web/src/modules/topic/utils/diagram.ts
web/src/modules/topic/utils/edge.ts
web/src/modules/topic/utils/nodes.ts

Closes #34 
- working with this, I think showing criteria in the problem view is too much. there are too many connections and it's very easy to be visually overwhelming. I think at this point it's worth merging still, but it seems likely that the criteria table view (as suggested in the issue's figma design) will completely replace any value that there is in this show/hiding of criteria in the problem view. in any case, this adds some value until that can be done, and a lot of the code needed to implement this will still be needed for future features.

34 showhide criteria

---

web/src/modules/topic/components/FlowNode/FlowNode.styles.tsx

- button group was using display: inherit, but the parent changed from EditableNode to FlowNode, and FlowNode just uses the default display: block. looked at Material UI's [example](https://mui.com/material-ui/react-button-group/#vertical-group) to see that flex is the intent
-

fix: claim buttons were showing horizontally

---

web/src/modules/topic/components/EditableNode/EditableNode.tsx

Closes #18
-  Added the auto focus functionality for editable nodes. The focus is granted to the editable text box on component initial mounting.  It currently doesn't work with the react-flow component. A new issue will be created to address the bug.
-

feat: editable nodes text box automatically focuses on component mount.

---

web/src/modules/topic/components/CriteriaTable/CriteriaTable.styles.tsx
web/src/modules/topic/components/CriteriaTable/CriteriaTable.tsx
web/src/modules/topic/utils/edge.ts

Closes #53
- Adds the Pivot Table / Table Transpose button to the Criteria Table Component. This allows the heading column and row to switch places.
- I refactored the column and row building methods to be more generic, and added transpose state to the component.
-

feat: topic criteria table transposes rows & columns

---

web/public/examples/economic_system.json
web/src/modules/topic/components/TopicToolbar/TopicToolbar.tsx

- watched [Capitalism vs Socialism debate video](https://www.youtube.com/watch?v=CVjgbFfaOJk) and tried to map out the problem, solutions, & arguments with ameliorate in order to identify improvements for the tool. Created a bunch of issues as a result (which are linked below)
Notes from this exercise:
- Score hover is really annoying
- Adding criteria from problem view is useful, so I don't have to leave the context to get to the table
- Problem node indicators are a little busy #60
- Allow more text in nodes, just use scroll?
- "…" seems to imply there's something there, but we're actually trimming it in data
- Adding too much text is still discouraged because it won't be easily visible
- Don't trim text when adding implicit claims #61
- Overlay could be a little more transparent… but …

docs: add economic system example

---

web/src/modules/topic/components/Score/Score.styles.tsx
web/src/modules/topic/components/Score/ScorePie.tsx

Closes #81
- Added functionality to segment mouse events,handles mouseleave and mouse hover events.
- Applies CSS to currently hovered segment.
- Selection wheel closes as soon as mouse leaves the pie chart.

fix: Score Dial appropriately closes

---

web/src/common/components/ContextMenu/ContextMenu.tsx
web/src/modules/topic/components/CriteriaTable/CriteriaTable.tsx
web/src/modules/topic/components/Node/AddNodeButton.tsx
web/src/modules/topic/store/actions.ts
web/src/modules/topic/utils/diagram.ts
web/src/modules/topic/utils/edge.ts

Closes #88 
- edges implied by detour nodes need to behave a little differently from edges implied by detour nodes - the latter do not care about relation direction
- implied edges were only being created on connect, not on add
- other commits are small fixes/touchups, see commit messages for details
-

88 connecting solution component to problem does not create implied problem solution edge

---

web/src/modules/topic/components/Score/Score.styles.tsx
web/src/modules/topic/components/Score/Score.tsx
web/src/modules/topic/components/Score/ScorePie.tsx

Revamped score component implementation 
-  Pie chart close event does not trigger for onMouseLeave & click away listener component.
- Backdrop component waits for mouse wheel / click / hover to remove pir chart.

fix: pie chart correctly closes

---

web/src/pages/index.page.tsx

- criteria diagram wasn't correctly overlaying the criteria table, zIndex was changed.

fix: criteria diagram correctly overlays table

---

web/src/modules/topic/components/CriteriaTable/CriteriaTable.styles.tsx
web/src/modules/topic/components/Node/EditableNode.styles.tsx
web/src/modules/topic/components/Node/EditableNode.tsx
web/src/modules/topic/components/Surface/TopicPane.styles.tsx
web/src/modules/topic/components/Surface/TopicPane.tsx

Partially Closes issue #74
-  Topic Pane Drawer correctly sits inside the workspace height space. It no longer over flows the top.
-  Editable node has been tidied up, extra space around text area has been removed, thus increasing the text area's available space
-  Criteria Table gained a box shadow effect on the bottom; this gives WOW factor.
- This should be merged into master before the REM unit changes.

Resizing editable node

---

README.md

- Add Contributions to the README.md 
- Example command: `@all-contributors please add @<username> for <contributions>`
- @all-contributors please add @alextilot for documentation

docs: add contributors to readme

---

web/src/modules/topic/components/Indicator/ClaimIndicator.tsx
web/src/modules/topic/components/Indicator/CriteriaTableIndicator.tsx
web/src/modules/topic/components/Indicator/Indicator.tsx

Closes #147 
The toolbar buttons and add node buttons already have tooltips, but the node indicator buttons do not yet. We should add these.
- 
-

Feature: Adde tooltip for view criteria table and view claims buttons

---

renovate.json5

get through all the upgrades in the renovate dashboard, make sure there good, before having a ton of PRs autocreated

chore: disable renovate

---

renovate.json5

separate group because nextjs 13.5 doesn't work with netlify, and they recommend (https://answers.netlify.com/t/runtime-importmoduleerror-error-cannot-find-module-styled-jsx-style/102375/10) staying on 13.4 until they can fix it

chore(renovate): separate nextjs

---

renovate.json5

previously we were grouping other `*next*` packages too, which was unintentional

chore(renovate): only group nextjs

---

scripts/setupLocal.sh

The first time I ran the setup script, it errored on `npm run db:start`, but it continued to run all the commands after that as well, which made it hard at the end to see what failed. `-e` makes it so that it stops execution if the script encounters an error. the shebang is optional but nice to have (and `shellcheck` reports not having it as an error), but not technically required as you call the script with `bash ...`
- minor improvements to setup script
-

Minor setup script improvements - add shebang and -e

---

src/common/edge.ts
src/common/node.ts
src/db/migrations/20231215093531_add_custom_edge_labels/down.sql
src/db/migrations/20231215093531_add_custom_edge_labels/migration.sql
src/db/migrations/20231215095650_add_relates_to_edge_type/down.sql
src/db/migrations/20231215095650_add_relates_to_edge_type/migration.sql
src/db/migrations/20231215124435_add_custom_node_type/down.sql
src/db/migrations/20231215124435_add_custom_node_type/migration.sql
src/db/schema.prisma
src/web/common/theme.ts
src/web/topic/components/Diagram/Diagram.tsx
src/web/topic/components/Edge/ScoreEdge.tsx
src/web/topic/components/Node/AddNodeButton.tsx
src/web/topic/components/Node/AddNodeButtonGroup.tsx
src/web/topic/components/Surface/MoreActionsDrawer.tsx
src/web/topic/components/TopicPane/SourceDetails.tsx
src/web/topic/store/actions.ts
src/web/topic/store/createDeleteActions.ts
src/web/topic/store/migrate.ts
src/web/topic/store/store.ts
src/web/topic/store/utils.ts
src/web/topic/store/viewActions.ts
src/web/topic/utils/apiConversion.ts
src/web/topic/utils/edge.ts
src/web/topic/utils/graph.ts
src/web/topic/utils/layout.ts
src/web/topic/utils/node.ts
src/web/view/actionConfigStore.ts

Closes #197 
- see commit messages; includes some small fixes in addition to unrestricted mode
-

Add unrestricted mode

---

src/common/node.ts
src/db/migrations/20231218132412_add_custom_node_labels/down.sql
src/db/migrations/20231218132412_add_custom_node_labels/migration.sql
src/db/schema.prisma
src/web/topic/components/Node/EditableNode.tsx
src/web/topic/store/actions.ts
src/web/topic/utils/apiConversion.ts
src/web/topic/utils/edge.ts
src/web/topic/utils/graph.ts

- also allow editing node type when unrestricted
-

Unrestrict node connections

---

src/web/topic/store/createDeleteActions.ts

previously was deleting the part's claim tree, but not claim trees for related parts also being deleted, e.g. edges tied to a node being deleted.
now all invalid claim trees will be deleted. seems easier to do this than to track specifically which trees need to be deleted.

fix: deleting node does not delete edge's claims

---

src/web/common/event.ts
src/web/view/navigateStore.ts

previously, if viewing a claim tree or criteria table, then switching to another topic (or resetting playground), the navigation store would still assume the topic diagram is in the background, so it wouldn't be interactive until refreshing page.
solution is just to reset navigation store on topic load (whose initial state has topic diagram in front).

fix: can't interact with diagram after switching

---

src/web/topic/components/Surface/MoreActionsDrawer.tsx
src/web/topic/hooks/diagramHooks.ts
src/web/topic/utils/layout.ts
src/web/view/actionConfigStore.ts

- some layouts are really complex and error or are visually bad to layout with partitioning on
-

touchup: allow disabling layout partitioning

---

package-lock.json
package.json
src/common/edge.ts
src/common/node.ts
src/web/common/components/ContextMenu/ChangeEdgeTypeMenuItem.tsx
src/web/common/components/ContextMenu/ChangeNodeTypeMenuItem.tsx
src/web/common/components/ContextMenu/ContextMenu.tsx
src/web/topic/components/Edge/ScoreEdge.tsx
src/web/topic/components/Node/EditableNode.tsx
src/web/topic/store/actions.ts
src/web/topic/utils/graph.ts

- some duplication but can refactor if more duplication is coming
- context-menu is somewhat hidden so didn't require unrestricted editing
-
- feedback from discourse session

feat: allow changing node/edge type

---

src/web/topic/utils/layout.ts

e.g. if an effect is not directly tied to a problem or solution, it wouldn't have been partitioned as expected.
-
-

fix: chained effects partition incorrectly

---

src/common/node.ts
src/web/topic/store/store.ts
src/web/topic/store/utils.ts
src/web/topic/utils/graph.ts
src/web/view/components/FilterOptions/FilterOptions.tsx
src/web/view/navigateStore.ts
src/web/view/utils/filter.ts

required moving context nodes out of explore diagram and into the diagram modification, so that they don't get filtered out by node types (wanted to keep node types select limited to types from the current diagram).
this seems preferable anyway so that we can just add a showContextNodes general filter option, to e.g. show questions in the topic diagram.
-
-

feat: add node types filter

---

src/common/node.ts
src/web/topic/components/Node/FlowNode.tsx
src/web/topic/store/actions.ts
src/web/topic/store/store.ts
src/web/topic/utils/graph.ts
src/web/topic/utils/layout.ts
src/web/view/actionConfigStore.ts
src/web/view/components/FilterOptions/FilterOptions.tsx
src/web/view/navigateStore.ts
src/web/view/utils/filter.ts

Fix change custom node doesnt clear type text

---

package-lock.json
package.json
src/web/topic/utils/layout.ts

also prefer laying out children closer to their parents.
also upgrade elkjs to 0.9.2 to allow using PREFER_NODES.
all tested layouts seem the same or improved. some layouts do not keep nodes grouped by type within layer, but these appear to significantly improve space usage.
-
- see [layout-decision topic](https://ameliorate.app/keyserj/layout-decision) for some reasonings, mainly for not sorting by edges, not using elkjs's `position`
- these topics were used to test layout differences:
[regular_appropriation_bill (6).json](https://github.com/amelioro/ameliorate/files/14513786/regular_appropriation_bill.6.json)
[us_political_system_issues.json](https://github.com/amelioro/ameliorate/files/14513787/us_political_system_issues.json) …

touchup: layout better by node type in layer

---

src/web/view/components/FilterOptions/FilterOptions.tsx

with a large diagram with multiple problems, this seems preferrable, with a small diagram with only one problem there's probably preference for defaulting to not show criteria/solutions, but it doesn't seem worth covering this case.
also, the general node type filter can remove solutions/criteria if users prefer that default.
-
-

touchup: default problem filter to all details

---

src/web/common/components/Layout.tsx

since docs are a different site, should not use client side routing
-
-

fix: link to release docs uses client side routing

---

package-lock.json
package.json
src/web/topic/components/Node/EditableNode.styles.tsx
src/web/topic/components/Node/EditableNode.tsx
src/web/topic/components/Node/FlowNode.styles.tsx
src/web/topic/components/Node/FlowNode.tsx
src/web/topic/components/Surface/MoreActionsDrawer.tsx
src/web/view/actionConfigStore.ts

Closes #360 
- add toggle (in MoreActionsDrawer) to choose not to fill the entire node with color
- also upgraded MUI to fix mui text area autosize error messages
the chosen option is: only color background of node icon, type, and border; this
- seems clear enough for a zoomed-out diagram with many nodes to be able to distinguish types still
- distinguishes node type from node text
- however, not sure how I feel about the node details, because node text is no longer well-distinguished from node notes (both white background)
<details>
<summary>Other considered options</summary>
- only highlight node icon and type; somewhat hard to see and awkwardly narrow coloring:
- only color background of node icon; neatly in the corner but hard to see:
- only color background of node icon and type: …

Node colors corner

---

docs-site/postcss.config.js

was caused by adding postcss in root nextjs project. added empty postcss config to prevent using postcss due to being configured in the root project.
-
-

fix: docs site postcss build error

---

src/web/view/quickViewStore/store.ts

reproduce by:
1. select quick view in topic A
2. switch to topic B, which has no quick views
3. make a view state change (e.g. turn force layers on/off)
observe "no view with id [id from topic A]" error in console
-
-

fix: keeps old selected view after load

---

src/web/topic/components/Node/NodeHandle.tsx

argument being that reveal-password buttons use this strategy. argument against could be that reveal-password buttons always work with asterisks, which indicate the password is being hidden, and the blue handle indicator isn't as obvious at showing hiddenness. But really it could go either way.
-
-

touchup: eye instead of eye-off for hidden nodes

---

src/web/topic/components/Surface/MoreActionsDrawer.tsx
src/web/topic/loadStores.ts
src/web/topic/store/migrate.ts
src/web/topic/store/store.ts
src/web/view/quickViewStore/store.ts

also extract download/upload logic to /topic/loadStores.ts because there's a lot of logic involved for it to live in a component.
Closes #421 
-
-

feat: include views in download/upload

---

src/web/topic/loadStores.ts
src/web/topic/store/utilActions.ts

also modified ensureUnique to do so by replacing id's via regex so that it's all-encompassing.
-
-

fix: upload doesn't replace ids for views

---

src/pages/[username].page.tsx
src/pages/notifications.page.tsx
src/web/comment/components/Comment.tsx
src/web/common/trpc.ts
src/web/topic/components/TopicPane/TopicDetails.tsx
src/web/topic/store/userHooks.ts

so far, no query needs to automatically refetch after some stale time. seems better to explicitly specify a stale time when we care to.
-
-

refactor: default reactquery staletime to infinity

---

package-lock.json
package.json
src/web/common/store/ephemeralStore.ts
src/web/topic/components/CriteriaTable/CriteriaTable.tsx
src/web/topic/components/CriteriaTable/NodeCell.tsx
src/web/topic/components/Edge/StandaloneEdge.tsx
src/web/topic/components/Node/AddNodeButton.tsx
src/web/topic/components/Node/AddNodeButtonGroup.tsx
src/web/topic/components/Node/EditableNode.tsx
src/web/topic/components/Node/FlowNode.styles.tsx
src/web/topic/components/Node/FlowNode.tsx
src/web/topic/components/Score/Score.tsx
src/web/topic/components/Surface/MoreActionsDrawer.tsx
src/web/topic/components/TopicPane/AnswerDetails.tsx
src/web/topic/components/TopicPane/DetailsClaimsSection.tsx
src/web/topic/components/TopicPane/DetailsResearchSection.tsx
src/web/topic/components/TopicPane/FactDetails.tsx
src/web/topic/components/TopicPane/GraphPartDetails.tsx
src/web/topic/components/TopicPane/QuestionDetails.tsx
src/web/topic/components/TopicPane/SourceDetails.tsx
src/web/topic/components/TopicWorkspace/TopicWorkspace.tsx
src/web/topic/store/actions.ts
src/web/topic/store/createDeleteActions.ts
src/web/topic/utils/graph.ts
src/web/topic/utils/hotkeys.ts
src/web/view/actionConfigStore.ts

Add read only mode

---

src/api/notifications/commentCreated.test.ts
src/api/notifications/commentCreated.ts
src/api/routers/comment.test.ts
src/common/inAppNotification.ts
src/db/migrations/20240619103802_remove_notification_reason/down.sql
src/db/migrations/20240619103802_remove_notification_reason/migration.sql
src/db/schema.prisma
src/pages/notifications.page.tsx
src/web/comment/components/Comment.tsx
src/web/topic/components/Surface/MoreActionsDrawer.tsx
src/web/topic/components/TopicPane/CommentSection.tsx
src/web/topic/components/TopicPane/TopicDetails.tsx

Watches only create subscriptions

---

src/web/common/event.ts
src/web/topic/components/Diagram/Diagram.tsx
src/web/topic/components/Indicator/Indicator.tsx
src/web/topic/components/Node/EditableNode.tsx
src/web/topic/components/Node/FlowNode.tsx
src/web/topic/components/TopicPane/TopicPane.tsx
src/web/topic/components/TopicWorkspace/TopicWorkspace.tsx
src/web/topic/hooks/flowHooks.ts
src/web/topic/utils/hotkeys.ts
src/web/view/currentViewStore/store.ts

Related #5 
-
- should be able to use most of the tool, between these shortcuts and vimium's `[fF]`-to-click functionality

Basic keyboard functionality

---

sentry.client.config.ts
src/instrumentation.page.ts
src/pages/new.page.tsx
src/web/comment/store/commentStore.ts
src/web/common/components/Layout.tsx
src/web/topic/components/Node/AddNodeButton.tsx
src/web/topic/components/TopicPane/CommentSection.tsx
src/web/topic/components/TopicPane/GraphPartDetails.tsx
src/web/topic/components/TopicPane/TopicViews.tsx
tailwind.config.js
tsconfig.json

Misc touchups 6

---

src/pages/_app.page.tsx
src/pages/index.page.tsx

before this, google results show "ameliorate.app" as name instead of the desired "Ameliorate".
-
-

touchup: influence seo to display site name

---

.vscode/settings.json
src/web/common/store/ephemeralStore.ts
src/web/topic/components/CriteriaTable/CriteriaTable.tsx
src/web/topic/components/CriteriaTable/NodeCell.tsx
src/web/topic/components/CriteriaTable/tableZoom.ts
src/web/topic/components/Edge/StandaloneEdge.tsx
src/web/topic/components/Node/AddNodeButton.tsx
src/web/topic/components/Node/AddNodeButtonGroup.tsx
src/web/topic/components/Node/EditableNode.tsx
src/web/topic/components/Node/FlowNode.tsx
src/web/topic/components/Score/Score.tsx
src/web/topic/components/TopicPane/AnswerDetails.tsx
src/web/topic/components/TopicPane/DetailsClaimsSection.tsx
src/web/topic/components/TopicPane/DetailsResearchSection.tsx
src/web/topic/components/TopicPane/FactDetails.tsx
src/web/topic/components/TopicPane/GraphPartDetails.tsx
src/web/topic/components/TopicPane/QuestionDetails.tsx
src/web/topic/components/TopicPane/SourceDetails.tsx
src/web/topic/components/TopicWorkspace/TopicWorkspace.tsx
src/web/topic/components/TopicWorkspace/WorkspaceContext.ts
src/web/topic/store/createDeleteActions.ts

Zoom criteria table mobile

---

src/web/topic/components/TopicWorkspace/TourHelper.tsx
src/web/tour/steps/diagramBasics.tsx
src/web/tour/tour.ts

figured out the positioning issues:
1. images were initially rendering as the size of the previously- loaded image. needed to set keys to ensure each image was getting its own size on initial render
2. `setSteps` without closing the tutorial was using the same popover size as the previously-seen step. needed to temporarily close the tutorial when switching steps.
-
-

touchup: position tutorial at bottom-right

---

src/web/home/Headline.tsx

fix: mobile headline is indented awkwardly

---

docs-site/next.config.js
docs-site/pages/discourse-sessions.mdx

also added another allowed remote image host for what seems like github's new asset URL
-
-

docs(discourse): add mention of tutorials

---

docs-site/next-env.d.ts
docs-site/package-lock.json
next-env.d.ts
package-lock.json
package.json

includes upgrading nextjs from 14.2.2 to 14.2.12
-
-

chore: npm audit fix

---

sentry.client.config.ts

annoying to send fetch envelopes every 5 seconds.
tried sampling only errors as well,
but that still sent envelopes every 5s.
don't think replays are really necessary anyway.
-
-

chore(sentry): turn off session replays

---

src/web/topic/store/createDeleteActions.ts
src/web/topic/utils/graph.ts

these edges were more annoying than anything else, e.g. more edges than necessary, more blue dots on solutions, more awkwardness if the edge from component to something is deleted.
a much better solution than auto-creating these will be #434.
-
-

touchup: stop auto creating composition edges

---

src/web/topic/utils/layout.ts

e.g. criterion context with parent effects will just have "relates to" edges without "created by" problem edges being shown. these should not be partitioned, so they can be above the criterion.
-
-

fix: don't partition effects with no created links

---

src/pages/[username]/[topicTitle].page.tsx

to reproduce:
1. create or open a topic you can edit
2. make some edits (add/remove nodes)
3. go to settings page
4. use back button to go back to your topic
5. observe your edits have been undone
this happened because the API request to load data for a topic was being kept fresh forever, so it would never re-request without a page refresh. once loaded with old data, the old data was saved, because all state changes are saved.
in this case, navigating using the back button would perform an SPA page navigation, reusing the data it was previously loaded with.
this bug was introduced by #441
-
-

fix: changes lost on navigate back

---

src/pages/_document.page.tsx
src/web/common/components/ContextMenu/AddNodeMenuItem.tsx
src/web/common/components/ContextMenu/ChangeEdgeTypeMenuItem.tsx
src/web/common/components/ContextMenu/ChangeNodeTypeMenuItem.tsx
src/web/common/components/Header.tsx
src/web/common/components/SubscribeForm/SubscribeForm.tsx
src/web/home/Footer.tsx
src/web/home/Headline.tsx
src/web/home/ImprovingSection.tsx
src/web/home/UseCasesSection.tsx
src/web/topic/components/Indicator/Indicator.tsx
src/web/topic/components/Node/EditableNode.styles.tsx
src/web/topic/components/Node/EditableNode.tsx
src/web/topic/components/TopicPane/DetailsJustificationSection.tsx
src/web/topic/components/TopicPane/DetailsResearchSection.tsx
src/web/topic/components/TopicPane/FactDetails.tsx
src/web/topic/components/TopicPane/NodeList.tsx
src/web/topic/components/TopicPane/QuestionDetails.tsx
src/web/topic/components/TopicPane/SourceDetails.tsx
src/web/topic/components/TopicWorkspace/WorkspaceToolbar.tsx
src/web/topic/utils/layout.ts

Fix layout not good for different default font sizes

---

.vscode/settings.json
src/api/notifications/commentCreated.test.ts
src/api/notifications/commentCreated.ts
src/common/node.ts
src/web/common/theme.ts
src/web/topic/components/Indicator/CommentIndicator.tsx
src/web/topic/components/Indicator/ContextIndicator.tsx
src/web/topic/components/Indicator/CriteriaTableIndicator.tsx
src/web/topic/components/Indicator/DetailsIndicator.tsx
src/web/topic/components/Indicator/ForceShownIndicator.tsx
src/web/topic/components/Indicator/FoundResearchIndicator.tsx
src/web/topic/components/Indicator/Indicator.tsx
src/web/topic/components/Indicator/JustificationIndicator.tsx
src/web/topic/components/Indicator/JustificationTreeIndicator.tsx
src/web/topic/components/Indicator/QuestionIndicator.tsx
src/web/topic/components/Node/EditableNode.styles.tsx
src/web/topic/components/Score/PieChart.tsx
src/web/topic/components/Score/ScoreButton.styles.tsx
src/web/topic/components/Score/ScoreButton.tsx
src/web/topic/components/TopicPane/GraphPartDetails.tsx
src/web/topic/components/TopicPane/TopicDetails.tsx
src/web/topic/utils/layout.ts
src/web/topic/utils/score.ts

Misc touchups 9

---

src/api/routers/notifications.ts
src/common/inAppNotification.ts
src/common/reservedEndpointNames.ts
src/db/migrations/20241105145536_retain_notifications_on_topic_deletion/down.sql
src/db/migrations/20241105145536_retain_notifications_on_topic_deletion/migration.sql
src/db/schema.prisma
src/pages/notifications.page.tsx
src/web/comment/store/apiSyncerMiddleware.ts
src/web/comment/store/commentStore.ts
src/web/common/theme.ts
src/web/topic/components/Edge/StandaloneEdge.tsx
src/web/topic/components/TopicPane/GraphPartDetails.tsx
src/web/topic/store/apiSyncerMiddleware.ts
src/web/topic/store/loadActions.ts
src/web/view/quickViewStore/apiSyncerMiddleware.ts
src/web/view/quickViewStore/store.ts

Closes #556 
- also misc changes, see commits
-

Fix store syncing unintentionally

---

src/web/topic/components/CriteriaTable/CriteriaTable.tsx
src/web/view/components/Filter/GeneralFilters.tsx

mainly so that right-click -> "hide node" is an alternative easy way to filter the table.
-
-

touchup: apply nodesToHide to criteria table

---

src/web/topic/utils/layout.ts

Could use the average-width to try and balance using too much space vs using too little space, but it doesn't seem like a big deal to use too much space, whereas labels still overlapping basically forfeits a lot of the value of trying to avoid overlap.
Related #569
-
-

touchup: increase edge label width for layout

---

src/web/topic/components/Edge/ScoreEdge.styles.tsx
src/web/topic/components/Edge/ScoreEdge.tsx
src/web/topic/components/Indicator/CommonIndicators.tsx
src/web/topic/components/Indicator/ContentIndicators.tsx
src/web/topic/components/Indicator/StatusIndicators.tsx
src/web/topic/components/Node/NodeHandle.tsx
src/web/topic/components/TopicWorkspace/TopicWorkspace.tsx
src/web/topic/components/TopicWorkspace/WorkspaceToolbar.tsx
src/web/topic/utils/hotkeys.ts
src/web/view/userConfigStore.ts

Partially addresses #478 .
Still TODO:
- default Zen mode on
- currently Zen mode is defaulted off, but I think if indicators show on-hover & on-select of node/edge, that it seems like it's likely worth defaulting. The diagram does look a lot cleaner, and new users won't know what the extras mean anyway. Hovering should allow them to discover the indicators if they haven't gone through the tutorial to figure out about Zen mode.
- update tutorial to point out Zen mode
If these are annoying, I might extract them to a follow-up ticket to do later.
-
-

Add zen mode

---

.eslintrc.json
docs-site/pages/getting-started/diagramming-basics.mdx
src/web/topic/components/Edge/ScoreEdge.tsx
src/web/topic/components/Indicator/CommonIndicators.tsx
src/web/topic/components/Indicator/ContentIndicators.tsx
src/web/topic/components/Indicator/Indicator.tsx
src/web/topic/components/Indicator/JustificationTreeIndicator.tsx
src/web/topic/components/Indicator/StatusIndicators.tsx
src/web/topic/components/Node/EditableNode.tsx
src/web/topic/components/Node/FlowNode.tsx
src/web/topic/components/Node/NodeHandle.tsx
src/web/topic/components/Score/Score.tsx
src/web/topic/components/Score/ScoreButton.tsx
src/web/topic/components/TopicWorkspace/TopicWorkspace.tsx
src/web/topic/components/TopicWorkspace/WorkspaceToolbar.tsx
src/web/topic/utils/hotkeys.ts
src/web/tutorial/steps/addingNuance.tsx
src/web/tutorial/steps/readingDiagram.tsx
src/web/view/currentViewStore/store.ts
src/web/view/userConfigStore.ts

Default indicators hidden

---

src/web/topic/components/Edge/ScoreEdge.tsx
src/web/topic/components/Node/EditableNode.styles.tsx
src/web/topic/components/Node/EditableNode.tsx

so they can be clicked by vimium
-
-

touchup: set role button for diagram parts

---

src/web/comment/store/commentStore.ts
src/web/common/components/ContextMenu/ViewDetailsMenuItem.tsx
src/web/common/event.ts
src/web/topic/components/Indicator/CommentIndicator.tsx
src/web/topic/components/Indicator/ContentIndicators.tsx
src/web/topic/components/Indicator/DetailsIndicator.tsx
src/web/topic/components/Indicator/FoundResearchIndicator.tsx
src/web/topic/components/Indicator/JustificationIndicator.tsx
src/web/topic/components/Indicator/QuestionIndicator.tsx
src/web/topic/components/TopicPane/CommentSection.tsx
src/web/topic/components/TopicPane/DetailsBasicsSection.tsx
src/web/topic/components/TopicPane/DetailsJustificationSection.tsx
src/web/topic/components/TopicPane/DetailsResearchSection.tsx
src/web/topic/components/TopicPane/GraphPartDetails.tsx
src/web/topic/components/TopicPane/TopicPane.tsx
src/web/topic/components/TopicWorkspace/MoreActionsDrawer.tsx
src/web/view/userConfigStore.ts

Closes #298 
- topic details hasn't been changed and still feels awkward, will try to think about that as part of #551

Use tabs for details pane

---

src/common/edge.ts
src/common/node.ts
src/db/migrations/20241216152339_add_mitigation_node/down.sql
src/db/migrations/20241216152339_add_mitigation_node/migration.sql
src/db/schema.prisma
src/web/common/theme.ts
src/web/topic/components/Diagram/Diagram.tsx
src/web/topic/components/Node/AddNodeButtonGroup.tsx
src/web/topic/store/nodeTypeHooks.ts
src/web/topic/utils/edge.ts
src/web/topic/utils/layout.ts
src/web/topic/utils/node.ts
src/web/view/utils/infoFilter.ts

Closes #549 
Not really sure if the extra complexity of Mitigation is worth it. The main value seems that we can treat mitigations as secondary/not-core, whereas solutions are core nodes and should stand out more. But there could be confusion about how to use mitigations, since solutions can accomplish a similar purpose.
We'll have to keep an eye out for how these feel - whether or not they seem worth the separate node type and logic.
-

Mitigation node

---

src/web/topic/components/TopicPane/GraphPartDetails.tsx
src/web/topic/components/TopicPane/TopicDetails.tsx
src/web/topic/components/TopicPane/TopicPane.tsx

a bunch of little things:
- use topic title for the heading
- move settings button into the heading
- create section for the Watch
- create Basics section for topic description
- put Basics and Comments sections behind tabs (based on expandDetailsTabs)
-
-

touchup: clean up topic details pane a bit

---

src/common/view.ts
src/web/view/quickViewStore/store.ts

`-Infinity` was passed over the API if all views were deleted, and a new one created.
Unfortunately Prisma serializes `-Infinity` as null (https://github.com/prisma/prisma/issues/19966#issuecomment-1658086903), so this API request was able to save as null in the db, rather than erroring as out of integer bounds.
Added `.finite()` to the zod schema to prevent this possibility in the future.
No other `number`s in schema allow null, so this is currently the only field that can have this issue, but we'll need to keep an eye out for it. `int`s that are conditionally `null` are susceptable.
To reproduce:
1. delete all views for a User Topic
2. create a new view (it'll be saved with `null` order in the db)
3. refresh page
4. delete the new view
5. observe error trying to delete the view because …

fix: can save view with no order

---

src/web/topic/utils/edge.ts

e.g. creating an edge from a solution's benefit to a problem's detriment should be "addresses", not "creates".

touchup: use "addresses" edges by default more

---

src/web/topic/utils/edge.ts

specifically for detriments
I just overlooked this. #244 probably would've prevented

fix: add-solution button is left of add-effects

---

.github/workflows/ci.yml

status check only errors if build errors. if deploy is cancelled e.g. because only docs-site was changed, the status check succeeds with text including "cancelled".
discovered on #624

fix: don't run e2e tests if deploy cancelled

---

src/web/common/components/ContextMenu/ChangeNodeTypeMenuItem.tsx

Closes #636 
- closely mirrored code developed during #633 for AddNodeMenuItem.tsx and applied it to ChangeNodeTypeMenuItem.tsx.

touchup(change node type drop down menu): applied icons and colors

---

src/web/topic/components/TopicPane/QuickViewSection.tsx
src/web/view/quickViewStore/store.ts

ideally would use something like pragmatic-drag-and-drop, but there's so much code for that, seemed not worth right now.
also considered dnd-kit, but that also seems like it isn't super well-maintained, and there was no example for dragging with keyboard.
Closes #422
-
-

feat: reorder quickviews

---

e2e/.eslintrc.json
e2e/tests/regression.spec.ts
e2e/tests/smoke.spec.ts
e2e/tests/utils.ts
e2e/tsconfig.json
tsconfig.json

buttons now displaying on node caused "solution new node" not to find the node in the details pane.
added tsconfig and eslintrc so that absolute paths can work in e2e/.

fix: smoke test not selecting right element

---

package-lock.json
package.json

for some reason npm audit actually didn't pick this up, but dependabot says it should be updated.
-
-

fix: npm audit fix vuln

---

src/web/common/components/SiteBanner/SiteBanner.tsx

fix: banner's "read more" leads to error page

---

package-lock.json

to address dependabot alerts.
-
- `npm audit` didn't find these, so I manually removed `packages."node_modules/tar-fs"` and `packages."node_modules/prebuild-install/node_modules/tar-fs"` from the package-lock.json, and ran `npm i`.

chore(deps): upgrade tar-fs

---

src/web/topic/utils/edge.ts

it seems like claims are better _not_ as standalone, and written in the context of their parents, but it seems ok to allow claims to have multiple parents, mainly for experimentation.
see context in discord thread https://discord.com/channels/1057707973482401892/1366783664771305492/1367138329547771905
-
-

touchup: allow claims to have two parents

---

src/web/topic/components/CriteriaTable/CriteriaTable.tsx
src/web/view/currentViewStore/store.ts

Closes #503
This PR addresses the issue of the transpose state (`useSolutionsForColumns`) in the CriteriaTable not persisting across page refreshes. The following changes have been made:
**Added `useSolutionsForColumns` to `ViewState`**
- Updated the `ViewState` interface to include`useSolutionsForColumns`
- Set the default value for useSolutionsForColumns in `initialViewState`.
**Created a Hook and Setter:**
- Added `useUseSolutionsForColumns` to retrieve the current state of `useSolutionsForColumns`.
- Added `setUseSolutionsForColumns` to update the state.
**Integrated with CriteriaTable:**
- Updated the CriteriaTable component to use the `useUseSolutionsForColumns` hook and `setUseSolutionsForColumns` setter.
- Ensured the transpose state persists across page refreshes and integrates …

feat: persist transpose state for CriteriaTable

---

src/web/topic/components/Node/EditableNode.tsx

totally hadn't thought of relying on `key` to ensure `defaultValue` updates the text if `label` changes externally.
-
-

fix: node forgets text when clicking textarea

---

src/web/topic/components/Edge/ScoreEdge.tsx

Previously, the "Delete edge" option in the context menu was only available when right-clicking on the edge label or certain parts of the edge path. 
- Added the `onContextMenu` handler to all interactive edge elements, "NOT" including the hidden interaction path and the move/drag handle.
- Ensured the correct edge context is passed to the context menu, so the "Delete edge" option is always available when right-clicking any part of the edge.
Users can now right-click anywhere on an edge—"NOT" including the move/drag handle—and always see the "Delete edge" option in the context menu, improving the editing workflow and consistency.
---

Delete option on edge

---

src/web/common/components/ContextMenu/AddNodeMenuItem.tsx
src/web/common/components/Menu/NestedMenuItem.tsx
src/web/topic/components/CriteriaTable/CriteriaTable.tsx
src/web/topic/components/Indicator/FoundResearchIndicator.tsx
src/web/topic/components/Indicator/JustificationIndicator.tsx
src/web/topic/components/Indicator/QuestionIndicator.tsx
src/web/topic/components/Score/Score.tsx
src/web/topic/components/Score/ScoreButton.tsx
src/web/topic/components/Score/ScoreCompare.tsx
src/web/topic/components/Score/ScoreSelect.tsx
src/web/topic/components/TopicWorkspace/ContentFooter.tsx
src/web/topic/diagramStore/scoreGetters.ts
src/web/topic/diagramStore/scoreHooks.ts
src/web/topic/diagramStore/store.ts
src/web/topic/utils/score.ts
src/web/view/perspectiveStore.ts

includes:
- add aggregation modes
- choose score colors by score meaning
- extract custom NestedMenuItem for consistent styling
considered using H/M/L instead of numbers for disagreement, so that they stand out clearly from regular scores, but those can't be trivially used with solution totals, so it seemed better to be consistent with using the same score numbers. potentially the score shape can distinguish disagreement in the future.
Closes #64
- see commit message
-

feat: add disagreement scores

---

src/web/topic/components/TopicPane/TopicPane.tsx

- woops, this was an unintentional result of https://github.com/amelioro/ameliorate/commit/950fbc688a44c42aeda4ddfeae08a17bdc9bd184
-

fix: details opens every time node is selected
